---
- name: ArangoDB 3.12 Install (Ubuntu 24.04 - Morpheus Day0)
  hosts: all
  become: true
  gather_facts: true

  vars:
    # Morpheus custom options (safe defaults)
    arango_root_password: "{{ hostvars[inventory_hostname]['morpheus']['customOptions']['dbCustomPassword'] | default('') }}"
    arango_db_name: "{{ hostvars[inventory_hostname]['morpheus']['customOptions']['dbCustomName'] | default('') }}"
    arango_db_user: "{{ hostvars[inventory_hostname]['morpheus']['customOptions']['dbCustomUser'] | default('') }}"
    arango_db_password: "{{ hostvars[inventory_hostname]['morpheus']['customOptions']['dbCustomPassword'] | default('') }}"

    # Repo + key (ArangoDB 3.12 example as you used)
    arango_repo_base: "https://download.arangodb.com/arangodb312/DEBIAN"
    arango_key_url: "https://download.arangodb.com/arangodb312/DEBIAN/Release.key"
    arango_keyring: "/usr/share/keyrings/arangodb.gpg"
    arango_repo: "deb [signed-by={{ arango_keyring }}] {{ arango_repo_base }}/ /"

    # Service / endpoint
    arango_endpoint: "tcp://127.0.0.1:8529"
    arango_port: 8529

  environment:
    DEBIAN_FRONTEND: noninteractive

  tasks:
    # --- Guardrails ---
    - name: Ensure target is Ubuntu 24.04
      ansible.builtin.fail:
        msg: "This playbook supports Ubuntu 24.04. Detected: {{ ansible_distribution }} {{ ansible_distribution_version }}"
      when: ansible_distribution != "Ubuntu" or ansible_distribution_version is not match("^24\\.04")

    # --- Prerequisites ---
    - name: Install prerequisites
      ansible.builtin.apt:
        name:
          - ca-certificates
          - curl
          - gnupg
        state: present
        update_cache: yes

    # --- Add repo (NO apt_key, NO get_url) ---
    - name: Create ArangoDB keyring using curl (bypass Python HTTPS)
      ansible.builtin.shell: |
        set -euo pipefail
        curl -fsSL "{{ arango_key_url }}" | gpg --dearmor -o "{{ arango_keyring }}"
        chmod 0644 "{{ arango_keyring }}"
      args:
        executable: /bin/bash
        creates: "{{ arango_keyring }}"

    - name: Add ArangoDB repository (signed-by)
      ansible.builtin.apt_repository:
        repo: "{{ arango_repo }}"
        state: present
        filename: arangodb

    - name: Update apt cache after adding repo
      ansible.builtin.apt:
        update_cache: yes

    # --- Install ArangoDB ---
    - name: Install ArangoDB package
      ansible.builtin.apt:
        name: arangodb3
        state: present

    # --- Configure bind endpoint + auth (idempotent) ---
    - name: Ensure endpoint binds to localhost:8529
      ansible.builtin.lineinfile:
        path: /etc/arangodb3/arangod.conf
        regexp: '^#?\s*endpoint\s*='
        line: "endpoint = {{ arango_endpoint }}"
        insertafter: '^\[server\]'

    - name: Enable authentication
      ansible.builtin.lineinfile:
        path: /etc/arangodb3/arangod.conf
        regexp: '^#?\s*authentication\s*='
        line: "authentication = true"
        insertafter: '^\[server\]'

    # --- Start service ---
    - name: Enable and start ArangoDB
      ansible.builtin.service:
        name: arangodb3
        enabled: yes
        state: restarted

    # --- If it doesn't start, fail with logs (so Morpheus output is useful) ---
    - name: Check service is active
      ansible.builtin.command: systemctl is-active arangodb3
      register: arango_active
      changed_when: false
      failed_when: false

    - name: Print status + journal if not active
      ansible.builtin.shell: |
        set +e
        echo "=== systemctl status arangodb3 ==="
        systemctl status arangodb3 --no-pager -l
        echo
        echo "=== journalctl -u arangodb3 (last 200 lines) ==="
        journalctl -u arangodb3 --no-pager -n 200
        echo
        echo "=== listening ports ==="
        ss -tulnp | grep -E '(:8529\b|arangod)' || true
      args:
        executable: /bin/bash
      register: arango_debug
      changed_when: false
      when: arango_active.stdout != "active"

    - name: Fail if ArangoDB service did not start
      ansible.builtin.fail:
        msg: |
          ArangoDB service is not active.
          {{ arango_debug.stdout }}
      when: arango_active.stdout != "active"

    # --- Wait until port is listening ---
    - name: Wait for ArangoDB port
      ansible.builtin.wait_for:
        host: 127.0.0.1
        port: "{{ arango_port }}"
        delay: 2
        timeout: 120

    # --- Set root password (optional) ---
    # NOTE: This assumes arangosh can connect locally. If your Arango build enforces auth immediately,
    # you may need a different bootstrap flow, but this works for many default installs.
    - name: Set ArangoDB root password (only if provided)
      ansible.builtin.shell: |
        set -euo pipefail
        arangosh \
          --server.endpoint "{{ arango_endpoint }}" \
          --javascript.execute-string "require('@arangodb/users').update('root', '{{ arango_root_password }}');"
      args:
        executable: /bin/bash
      when: arango_root_password != ""

    # --- Create DB + user (optional) ---
    - name: Create DB + user if provided
      block:
        - name: Create database
          ansible.builtin.shell: |
            set -euo pipefail
            arangosh \
              --server.endpoint "{{ arango_endpoint }}" \
              --server.username root \
              --server.password "{{ arango_root_password }}" \
              --javascript.execute-string "db._createDatabase('{{ arango_db_name }}');"
          args:
            executable: /bin/bash

        - name: Create user
          ansible.builtin.shell: |
            set -euo pipefail
            arangosh \
              --server.endpoint "{{ arango_endpoint }}" \
              --server.username root \
              --server.password "{{ arango_root_password }}" \
              --javascript.execute-string "require('@arangodb/users').save('{{ arango_db_user }}', '{{ arango_db_password }}');"
          args:
            executable: /bin/bash

        - name: Grant user access
          ansible.builtin.shell: |
            set -euo pipefail
            arangosh \
              --server.endpoint "{{ arango_endpoint }}" \
              --server.username root \
              --server.password "{{ arango_root_password }}" \
              --javascript.execute-string "require('@arangodb/users').grantDatabase('{{ arango_db_user }}', '{{ arango_db_name }}');"
          args:
            executable: /bin/bash
      when:
        - arango_db_name != ""
        - arango_db_user != ""
        - arango_db_password != ""
        - arango_root_password != ""

    - name: Done
      ansible.builtin.debug:
        msg: "ArangoDB installed and running on {{ arango_endpoint }} (auth enabled)."
