---
- name: ArangoDB 3.12 Install (Ubuntu 24.04 - Morpheus Day0)
  hosts: all
  become: true
  gather_facts: true

  vars:
    arango_root_password: "{{ hostvars[inventory_hostname]['morpheus']['customOptions']['dbCustomPassword'] | default('') }}"
    arango_db_name: "{{ hostvars[inventory_hostname]['morpheus']['customOptions']['dbCustomName'] | default('') }}"
    arango_db_user: "{{ hostvars[inventory_hostname]['morpheus']['customOptions']['dbCustomUser'] | default('') }}"
    arango_db_password: "{{ hostvars[inventory_hostname]['morpheus']['customOptions']['dbCustomPassword'] | default('') }}"

    arango_repo_base: "https://download.arangodb.com/arangodb312/DEBIAN"
    arango_key_url: "https://download.arangodb.com/arangodb312/DEBIAN/Release.key"
    arango_keyring: "/usr/share/keyrings/arangodb.gpg"
    arango_repo: "deb [signed-by={{ arango_keyring }}] {{ arango_repo_base }}/ /"

    arango_endpoint: "tcp://127.0.0.1:8529"
    arango_port: 8529

  environment:
    DEBIAN_FRONTEND: noninteractive

  tasks:
    - name: Install prerequisites
      ansible.builtin.apt:
        name:
          - ca-certificates
          - curl
          - gnupg
        state: present
        update_cache: yes

    - name: Create ArangoDB keyring using curl (bypass Python HTTPS)
      ansible.builtin.shell: |
        set -euo pipefail
        curl -fsSL "{{ arango_key_url }}" | gpg --dearmor -o "{{ arango_keyring }}"
        chmod 0644 "{{ arango_keyring }}"
      args:
        executable: /bin/bash
        creates: "{{ arango_keyring }}"

    - name: Add ArangoDB repository (signed-by)
      ansible.builtin.apt_repository:
        repo: "{{ arango_repo }}"
        state: present
        filename: arangodb

    - name: Update apt cache after adding repo
      ansible.builtin.apt:
        update_cache: yes

    - name: Install ArangoDB package
      ansible.builtin.apt:
        name: arangodb3
        state: present

    # --- Configure bind/auth BEFORE starting ---
    - name: Ensure endpoint binds to localhost:8529
      ansible.builtin.lineinfile:
        path: /etc/arangodb3/arangod.conf
        regexp: '^#?\s*endpoint\s*='
        line: "endpoint = {{ arango_endpoint }}"
        insertafter: '^\[server\]'

    - name: Enable authentication
      ansible.builtin.lineinfile:
        path: /etc/arangodb3/arangod.conf
        regexp: '^#?\s*authentication\s*='
        line: "authentication = true"
        insertafter: '^\[server\]'

    # --- Start service (first attempt) ---
    - name: Enable and start ArangoDB (first attempt)
      ansible.builtin.service:
        name: arangodb3
        enabled: yes
        state: started

    - name: Check service is active (first attempt)
      ansible.builtin.command: systemctl is-active arangodb3
      register: arango_active_1
      changed_when: false
      failed_when: false

    # --- If it failed, check journal for the language mismatch and wipe stale data dirs ---
    - name: Read journal for language mismatch (only if not active)
      ansible.builtin.shell: |
        set +e
        journalctl -u arangodb3 --no-pager -n 200 | tail -n 200
      args:
        executable: /bin/bash
      register: arango_journal_1
      changed_when: false
      when: arango_active_1.stdout != "active"

    - name: Stop ArangoDB before wiping stale data (only if language mismatch)
      ansible.builtin.service:
        name: arangodb3
        state: stopped
      when:
        - arango_active_1.stdout != "active"
        - arango_journal_1.stdout is search("Specified language 'en_US'")

    - name: Wipe stale ArangoDB data dirs from template (only if language mismatch)
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - /var/lib/arangodb3
        - /var/lib/arangodb3-apps
      when:
        - arango_active_1.stdout != "active"
        - arango_journal_1.stdout is search("Specified language 'en_US'")

    - name: Recreate ArangoDB data dirs (only if wiped)
      ansible.builtin.shell: |
        set -e
        install -d -o arangodb -g arangodb -m 0700 /var/lib/arangodb3
        install -d -o arangodb -g arangodb -m 0700 /var/lib/arangodb3-apps
      args:
        executable: /bin/bash
      changed_when: true
      when:
        - arango_active_1.stdout != "active"
        - arango_journal_1.stdout is search("Specified language 'en_US'")

    - name: Start ArangoDB (second attempt after wipe)
      ansible.builtin.service:
        name: arangodb3
        state: started
        enabled: yes

    - name: Check service is active (second attempt)
      ansible.builtin.command: systemctl is-active arangodb3
      register: arango_active_2
      changed_when: false
      failed_when: false

    - name: Fail with status + journal if still not active
      ansible.builtin.shell: |
        set +e
        echo "=== systemctl status arangodb3 ==="
        systemctl status arangodb3 --no-pager -l
        echo
        echo "=== journalctl -u arangodb3 (last 200 lines) ==="
        journalctl -u arangodb3 --no-pager -n 200
      args:
        executable: /bin/bash
      register: arango_debug
      changed_when: false
      when: arango_active_2.stdout != "active"

    - name: Fail if ArangoDB service did not start
      ansible.builtin.fail:
        msg: |
          ArangoDB service is not active after retry.
          {{ arango_debug.stdout }}
      when: arango_active_2.stdout != "active"

    - name: Wait for ArangoDB port
      ansible.builtin.wait_for:
        host: 127.0.0.1
        port: "{{ arango_port }}"
        delay: 2
        timeout: 120

    - name: Set ArangoDB root password (only if provided)
      ansible.builtin.shell: |
        set -euo pipefail
        arangosh \
          --server.endpoint "{{ arango_endpoint }}" \
          --javascript.execute-string "require('@arangodb/users').update('root', '{{ arango_root_password }}');"
      args:
        executable: /bin/bash
      when: arango_root_password != ""

    - name: Create DB + user if provided
      block:
        - name: Create database
          ansible.builtin.shell: |
            set -euo pipefail
            arangosh \
              --server.endpoint "{{ arango_endpoint }}" \
              --server.username root \
              --server.password "{{ arango_root_password }}" \
              --javascript.execute-string "db._createDatabase('{{ arango_db_name }}');"
          args:
            executable: /bin/bash

        - name: Create user
          ansible.builtin.shell: |
            set -euo pipefail
            arangosh \
              --server.endpoint "{{ arango_endpoint }}" \
              --server.username root \
              --server.password "{{ arango_root_password }}" \
              --javascript.execute-string "require('@arangodb/users').save('{{ arango_db_user }}', '{{ arango_db_password }}');"
          args:
            executable: /bin/bash

        - name: Grant user access
          ansible.builtin.shell: |
            set -euo pipefail
            arangosh \
              --server.endpoint "{{ arango_endpoint }}" \
              --server.username root \
              --server.password "{{ arango_root_password }}" \
              --javascript.execute-string "require('@arangodb/users').grantDatabase('{{ arango_db_user }}', '{{ arango_db_name }}');"
          args:
            executable: /bin/bash
      when:
        - arango_db_name != ""
        - arango_db_user != ""
        - arango_db_password != ""
        - arango_root_password != ""
