---
# File: arangodb_morpheus_ubuntu24_full_WORKING.yml
# Target: Ubuntu 24.04 (QCOW2) in Morpheus
# Fixes:
# - Avoids Ansible get_url (requests/urllib3 mismatch) -> uses curl
# - Ensures clean initialization on FIRST run to avoid template leftovers
# - Adds robust diagnostics when systemd start fails

- name: Install and configure ArangoDB on Ubuntu 24.04 (Morpheus)
  hosts: all
  become: true
  gather_facts: true

  vars:
    ansible_python_interpreter: /usr/bin/python3

    # ===== Morpheus overrides (optional) =====
    arango_root_password: "{{ hostvars[inventory_hostname]['morpheus']['customOptions']['arangoRootPassword'] | default('ChangeMe_Strong_Passw0rd!') }}"
    arango_bind_ip: "{{ hostvars[inventory_hostname]['morpheus']['customOptions']['arangoBindIp'] | default('0.0.0.0') }}"
    arango_port: "{{ hostvars[inventory_hostname]['morpheus']['customOptions']['arangoPort'] | default('8529') }}"
    arango_enable_auth: "{{ hostvars[inventory_hostname]['morpheus']['customOptions']['arangoAuth'] | default(true) | bool }}"

    # If true -> ALWAYS wipe data dirs (dangerous for existing data)
    arango_force_reinit: "{{ hostvars[inventory_hostname]['morpheus']['customOptions']['arangoForceReinit'] | default(false) | bool }}"

    # Marker to make "wipe on first run" idempotent
    arango_init_marker: "/var/lib/arangodb3/.morpheus_initialized"

    # ===== Repo settings (ArangoDB 3.12 line) =====
    arango_repo_path: "arangodb312"
    arango_repo_url: "https://download.arangodb.com/{{ arango_repo_path }}/DEBIAN/"
    arango_key_url: "https://download.arangodb.com/{{ arango_repo_path }}/DEBIAN/Release.key"
    arango_keyring_path: "/usr/share/keyrings/arangodb.gpg"
    arango_sources_list: "/etc/apt/sources.list.d/arangodb.list"

    # Firewall (optional)
    arango_manage_ufw: "{{ hostvars[inventory_hostname]['morpheus']['customOptions']['arangoManageUfw'] | default(false) | bool }}"

  handlers:
    - name: restart arangodb
      ansible.builtin.systemd:
        name: arangodb3
        state: restarted
        enabled: true
        daemon_reload: true

  tasks:
    # -----------------------------
    # Base packages
    # -----------------------------
    - name: Ensure required packages are installed
      ansible.builtin.apt:
        name:
          - ca-certificates
          - curl
          - gnupg
          - apt-transport-https
        state: present
        update_cache: true

    # -----------------------------
    # Repo key + repo (curl-based)
    # -----------------------------
    - name: Download ArangoDB Release.key using curl
      ansible.builtin.shell: |
        set -euo pipefail
        curl -fsSL "{{ arango_key_url }}" -o /tmp/arangodb-Release.key
      args:
        executable: /bin/bash
      changed_when: false

    - name: Install ArangoDB key into keyring (signed-by)
      ansible.builtin.command: >
        gpg --dearmor -o {{ arango_keyring_path }} /tmp/arangodb-Release.key
      args:
        creates: "{{ arango_keyring_path }}"

    - name: Ensure keyring permissions are correct
      ansible.builtin.file:
        path: "{{ arango_keyring_path }}"
        owner: root
        group: root
        mode: "0644"

    - name: Add ArangoDB APT repository (signed-by keyring)
      ansible.builtin.copy:
        dest: "{{ arango_sources_list }}"
        owner: root
        group: root
        mode: "0644"
        content: |
          deb [signed-by={{ arango_keyring_path }}] {{ arango_repo_url }} /
      register: arango_repo_file

    - name: Update apt cache after adding ArangoDB repo
      ansible.builtin.apt:
        update_cache: true
      when: arango_repo_file.changed

    # -----------------------------
    # Install
    # -----------------------------
    - name: Install ArangoDB
      ansible.builtin.apt:
        name: arangodb3
        state: present

    # IMPORTANT: Stop service right away to avoid crash-loop during provisioning
    - name: Stop ArangoDB right after install (avoid crash-loop during provisioning)
      ansible.builtin.systemd:
        name: arangodb3
        state: stopped
      failed_when: false

    - name: Ensure ArangoDB enabled
      ansible.builtin.systemd:
        name: arangodb3
        enabled: true

    # -----------------------------
    # Configure arangod.conf
    # -----------------------------
    - name: Configure server endpoint (bind IP + port)
      ansible.builtin.lineinfile:
        path: /etc/arangodb3/arangod.conf
        regexp: '^\s*endpoint\s*='
        line: "endpoint = tcp://{{ arango_bind_ip }}:{{ arango_port }}"
      notify: restart arangodb

    - name: Ensure any commented endpoint line is not accidentally used (no-op safety)
      ansible.builtin.replace:
        path: /etc/arangodb3/arangod.conf
        regexp: '^\s*#\s*endpoint\s*='
        replace: 'endpoint ='
      notify: restart arangodb

    - name: Configure authentication
      ansible.builtin.lineinfile:
        path: /etc/arangodb3/arangod.conf
        regexp: '^\s*authentication\s*='
        line: "authentication = {{ 'true' if arango_enable_auth else 'false' }}"
      notify: restart arangodb

    # -----------------------------
    # Clean init logic (FIRST run)
    # -----------------------------
    - name: Check if Morpheus init marker exists
      ansible.builtin.stat:
        path: "{{ arango_init_marker }}"
      register: arango_marker

    - name: Determine if we must re-initialize data dirs
      ansible.builtin.set_fact:
        arango_need_reinit: "{{ arango_force_reinit or (not arango_marker.stat.exists) }}"
      changed_when: false

    - name: Remove ArangoDB data dirs for first-run clean init (or forced)
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - /var/lib/arangodb3
        - /var/lib/arangodb3-apps
      when: arango_need_reinit

    - name: Recreate data dirs with correct ownership (avoid permission issues)
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: arangodb
        group: arangodb
        mode: "0700"
      loop:
        - /var/lib/arangodb3
        - /var/lib/arangodb3-apps
      when: arango_need_reinit

    # -----------------------------
    # Start service (with diagnostics)
    # -----------------------------
    - name: Start ArangoDB (capture logs if it fails)
      block:
        - name: Start arangodb3 service
          ansible.builtin.systemd:
            name: arangodb3
            state: started
            enabled: true

        - name: Wait for ArangoDB port to be reachable locally
          ansible.builtin.wait_for:
            host: "127.0.0.1"
            port: "{{ arango_port | int }}"
            delay: 1
            timeout: 90

      rescue:
        - name: systemctl status arangodb3
          ansible.builtin.command: "systemctl status arangodb3 --no-pager -l"
          register: arango_status
          changed_when: false
          failed_when: false

        - name: journalctl -xeu arangodb3
          ansible.builtin.command: "journalctl -xeu arangodb3 --no-pager -n 250"
          register: arango_journal
          changed_when: false
          failed_when: false

        - name: show endpoint/auth lines from config
          ansible.builtin.command: "egrep -n '^\\s*(#\\s*)?(endpoint|authentication)\\s*=' /etc/arangodb3/arangod.conf"
          register: conf_lines
          changed_when: false
          failed_when: false

        - name: socket listeners
          ansible.builtin.command: "ss -lntp"
          register: ss_out
          changed_when: false
          failed_when: false

        - name: Fail with diagnostics
          ansible.builtin.fail:
            msg: |
              Unable to start ArangoDB (arangodb3).

              --- systemctl status ---
              {{ arango_status.stdout | default('') }}

              --- journalctl -xeu arangodb3 (last 250) ---
              {{ arango_journal.stdout | default('') }}

              --- arangod.conf (endpoint/auth) ---
              {{ conf_lines.stdout | default('') }}

              --- ss -lntp ---
              {{ ss_out.stdout | default('') }}

    # -----------------------------
    # Create marker AFTER successful start (so we don't wipe again)
    # -----------------------------
    - name: Create Morpheus init marker after successful start
      ansible.builtin.file:
        path: "{{ arango_init_marker }}"
        state: touch
        owner: arangodb
        group: arangodb
        mode: "0600"
      when: arango_need_reinit

    # -----------------------------
    # Root password (idempotent)
    # -----------------------------
    - name: Check if root password already works (local arangosh)
      ansible.builtin.command: >
        arangosh
        --server.endpoint tcp://127.0.0.1:{{ arango_port }}
        --server.username root
        --server.password {{ arango_root_password | quote }}
        --javascript.execute-string "print('ok')"
      register: arango_pw_check
      changed_when: false
      failed_when: false

    - name: Set root password if needed (arango-passwd)
      ansible.builtin.command: >
        arango-passwd --user root --password {{ arango_root_password | quote }}
      when: arango_pw_check.rc != 0
      notify: restart arangodb

    - name: Restart after password set (if changed)
      ansible.builtin.meta: flush_handlers

    # -----------------------------
    # Optional UFW rule
    # -----------------------------
    - name: Check ufw status (if installed)
      ansible.builtin.command: ufw status
      register: ufw_status
      changed_when: false
      failed_when: false

    - name: Allow ArangoDB port in ufw (only if active OR arango_manage_ufw=true)
      ansible.builtin.command: "ufw allow {{ arango_port }}/tcp"
      when:
        - ufw_status.rc == 0
        - (arango_manage_ufw | bool) or ('Status: active' in ufw_status.stdout)

    # -----------------------------
    # Final verification
    # -----------------------------
    - name: Verify HTTP version endpoint locally
      ansible.builtin.shell: |
        set -euo pipefail
        curl -fsS "http://127.0.0.1:{{ arango_port }}/_api/version" | head -c 500
      args:
        executable: /bin/bash
      register: arango_version_http
      changed_when: false

    - name: Show access info
      ansible.builtin.debug:
        msg:
          - "ArangoDB installed and running."
          - "Web UI: http://<server-ip>:{{ arango_port }}"
          - "Root user: root"
          - "Auth enabled: {{ arango_enable_auth }}"
          - "Version endpoint output (truncated): {{ arango_version_http.stdout }}"
