---
# File: arangodb_morpheus_ubuntu24_fixed.yml
# Fix: avoids ansible get_url (requests/urllib3 mismatch on some images) by using curl

- name: Install and configure ArangoDB on Ubuntu 24.04 (Morpheus)
  hosts: all
  become: true
  gather_facts: true

  vars:
    ansible_python_interpreter: /usr/bin/python3

    # Morpheus overrides (optional)
    arango_root_password: "{{ hostvars[inventory_hostname]['morpheus']['customOptions']['arangoRootPassword'] | default('ChangeMe_Strong_Passw0rd!') }}"
    arango_bind_ip: "{{ hostvars[inventory_hostname]['morpheus']['customOptions']['arangoBindIp'] | default('0.0.0.0') }}"
    arango_port: "{{ hostvars[inventory_hostname]['morpheus']['customOptions']['arangoPort'] | default('8529') }}"
    arango_enable_auth: "{{ hostvars[inventory_hostname]['morpheus']['customOptions']['arangoAuth'] | default(true) | bool }}"

    # ArangoDB repo (3.12 line)
    arango_repo_path: "arangodb312"
    arango_repo_url: "https://download.arangodb.com/{{ arango_repo_path }}/DEBIAN/"
    arango_key_url: "https://download.arangodb.com/{{ arango_repo_path }}/DEBIAN/Release.key"
    arango_keyring_path: "/usr/share/keyrings/arangodb.gpg"
    arango_sources_list: "/etc/apt/sources.list.d/arangodb.list"

    # Firewall (optional)
    arango_manage_ufw: false

  handlers:
    - name: restart arangodb
      ansible.builtin.systemd:
        name: arangodb3
        state: restarted
        enabled: true
        daemon_reload: true

  tasks:
    - name: Ensure required packages are installed
      ansible.builtin.apt:
        name:
          - ca-certificates
          - curl
          - gnupg
          - apt-transport-https
        state: present
        update_cache: true

    # ---- Key download WITHOUT get_url ----
    - name: Download ArangoDB Release.key using curl (bypass python requests/urllib3)
      ansible.builtin.shell: |
        set -euo pipefail
        curl -fsSL "{{ arango_key_url }}" -o /tmp/arangodb-Release.key
      args:
        executable: /bin/bash
      changed_when: false

    - name: Install ArangoDB key into keyring (signed-by)
      ansible.builtin.command: >
        gpg --dearmor -o {{ arango_keyring_path }} /tmp/arangodb-Release.key
      args:
        creates: "{{ arango_keyring_path }}"

    - name: Ensure keyring permissions are correct
      ansible.builtin.file:
        path: "{{ arango_keyring_path }}"
        owner: root
        group: root
        mode: "0644"

    - name: Add ArangoDB APT repository (signed-by keyring)
      ansible.builtin.copy:
        dest: "{{ arango_sources_list }}"
        owner: root
        group: root
        mode: "0644"
        content: |
          deb [signed-by={{ arango_keyring_path }}] {{ arango_repo_url }} /
      register: arango_repo_file

    - name: Update apt cache after adding ArangoDB repo
      ansible.builtin.apt:
        update_cache: true
      when: arango_repo_file.changed

    - name: Install ArangoDB
      ansible.builtin.apt:
        name: arangodb3
        state: present

    - name: Ensure ArangoDB service is enabled + started
      ansible.builtin.systemd:
        name: arangodb3
        state: started
        enabled: true

    # ---- Configure arangod.conf ----
    - name: Configure server endpoint (bind IP + port)
      ansible.builtin.lineinfile:
        path: /etc/arangodb3/arangod.conf
        regexp: '^\s*endpoint\s*='
        line: "endpoint = tcp://{{ arango_bind_ip }}:{{ arango_port }}"
      notify: restart arangodb

    - name: Configure authentication
      ansible.builtin.lineinfile:
        path: /etc/arangodb3/arangod.conf
        regexp: '^\s*authentication\s*='
        line: "authentication = {{ 'true' if arango_enable_auth else 'false' }}"
      notify: restart arangodb

    - name: Apply restart if config changed
      ansible.builtin.meta: flush_handlers

    # ---- Root password (idempotent) ----
    - name: Check if root password already works (local arangosh)
      ansible.builtin.command: >
        arangosh
        --server.endpoint tcp://127.0.0.1:{{ arango_port }}
        --server.username root
        --server.password {{ arango_root_password | quote }}
        --javascript.execute-string "print('ok')"
      register: arango_pw_check
      changed_when: false
      failed_when: false

    - name: Set root password if needed (arango-passwd)
      ansible.builtin.command: >
        arango-passwd --user root --password {{ arango_root_password | quote }}
      when: arango_pw_check.rc != 0
      notify: restart arangodb

    - name: Apply restart after password set (if needed)
      ansible.builtin.meta: flush_handlers

    # ---- Optional UFW rule ----
    - name: Check ufw status (if installed)
      ansible.builtin.command: ufw status
      register: ufw_status
      changed_when: false
      failed_when: false

    - name: Allow ArangoDB port in ufw (only if active OR arango_manage_ufw=true)
      ansible.builtin.command: "ufw allow {{ arango_port }}/tcp"
      when:
        - ufw_status.rc == 0
        - (arango_manage_ufw | bool) or ('Status: active' in ufw_status.stdout)


        
    - name: Check for language mismatch crash in journal (last 200 lines)
      ansible.builtin.command: "journalctl -u arangodb3 -n 200 --no-pager"
      register: arango_journal_check
      changed_when: false
      failed_when: false

    - name: Stop ArangoDB if it is crash-looping
      ansible.builtin.systemd:
        name: arangodb3
        state: stopped
      when: "'does not match previously used language' in arango_journal_check.stdout"

    - name: Remove ArangoDB data dirs to re-initialize cleanly (fix language mismatch)
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - /var/lib/arangodb3
        - /var/lib/arangodb3-apps
      when: "'does not match previously used language' in arango_journal_check.stdout"

    - name: Start ArangoDB after re-init
      ansible.builtin.systemd:
        name: arangodb3
        state: started
        enabled: true
      when: "'does not match previously used language' in arango_journal_check.stdout"

    # ---- Validation ----
    - name: Wait for ArangoDB port to be reachable locally
      ansible.builtin.wait_for:
        host: "127.0.0.1"
        port: "{{ arango_port | int }}"
        delay: 1
        timeout: 60

    - name: Show access info
      ansible.builtin.debug:
        msg:
          - "ArangoDB installed and running."
          - "Web UI: http://<server-ip>:{{ arango_port }}"
          - "Root user: root"
          - "Auth enabled: {{ arango_enable_auth }}"
