---
- name: Install and Configure ArangoDB (Ubuntu 24 - Morpheus)
  hosts: all
  become: yes
  gather_facts: yes

  vars:
    db_password: "{{ hostvars[inventory_hostname]['morpheus']['customOptions']['dbCustomPassword'] | default('') }}"
    db_user: "{{ hostvars[inventory_hostname]['morpheus']['customOptions']['dbCustomUser'] | default('') }}"
    db_name: "{{ hostvars[inventory_hostname]['morpheus']['customOptions']['dbCustomName'] | default('') }}"
    root_password: "{{ hostvars[inventory_hostname]['morpheus']['customOptions']['dbCustomPassword'] | default('') }}"

    arangodb_repo_base: "https://download.arangodb.com/arangodb312/DEBIAN"
    arangodb_key_url: "https://download.arangodb.com/arangodb312/DEBIAN/Release.key"
    arangodb_keyring_path: "/usr/share/keyrings/arangodb.gpg"
    arangodb_repo_line: "deb [signed-by={{ arangodb_keyring_path }}] {{ arangodb_repo_base }}/ /"

  environment:
    DEBIAN_FRONTEND: noninteractive

  tasks:
    - name: Fail if not Ubuntu
      ansible.builtin.fail:
        msg: "Not Ubuntu. Detected: {{ ansible_distribution }} {{ ansible_distribution_version }}"
      when: ansible_distribution != "Ubuntu"

    - name: Install prerequisites (curl, gnupg, ca-certificates)
      ansible.builtin.apt:
        name:
          - ca-certificates
          - curl
          - gnupg
        state: present
        update_cache: yes

    - name: Create ArangoDB keyring using curl (bypass Python HTTPS)
      ansible.builtin.shell: |
        set -euo pipefail
        curl -fsSL "{{ arangodb_key_url }}" | gpg --dearmor -o "{{ arangodb_keyring_path }}"
        chmod 0644 "{{ arangodb_keyring_path }}"
      args:
        executable: /bin/bash
        creates: "{{ arangodb_keyring_path }}"

    - name: Add ArangoDB repository (signed-by keyring)
      ansible.builtin.apt_repository:
        repo: "{{ arangodb_repo_line }}"
        state: present
        filename: arangodb

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600

    # Ensure no interactive prompts block install
    - name: Install ArangoDB
      ansible.builtin.apt:
        name: arangodb3
        state: present
      register: arango_install

    - name: Show install output (debug)
      ansible.builtin.debug:
        var: arango_install
      changed_when: false

    - name: Enable and start ArangoDB service
      ansible.builtin.service:
        name: arangodb3
        state: started
        enabled: yes

    # Quick health check: show service + logs BEFORE wait_for, so we don't fail blind
    - name: Check arangodb3 service status (no fail)
      ansible.builtin.shell: |
        set +e
        systemctl status arangodb3 --no-pager -l
        echo "---- journalctl (last 200 lines) ----"
        journalctl -u arangodb3 --no-pager -n 200
        echo "---- listening ports ----"
        ss -tulnp | grep -E '(:8529\b|arangod)' || true
        echo "---- config snippet ----"
        grep -nE '^\[server\]|^endpoint|^authentication|^#?authentication' /etc/arangodb3/arangod.conf || true
      args:
        executable: /bin/bash
      register: arango_diag_pre
      changed_when: false

    - name: Print diagnostics (pre-wait)
      ansible.builtin.debug:
        msg: "{{ arango_diag_pre.stdout }}"

    # Wait longer (first boot can be slow)
    - name: Wait for ArangoDB to be ready on 127.0.0.1:8529
      ansible.builtin.wait_for:
        host: 127.0.0.1
        port: 8529
        delay: 5
        timeout: 240

    # Enable auth (do this after it's confirmed up)
    - name: Enable authentication in ArangoDB configuration
      ansible.builtin.lineinfile:
        path: /etc/arangodb3/arangod.conf
        regexp: '^#?\s*authentication\s*='
        line: 'authentication = true'
        insertafter: '^\[server\]'

    - name: Restart ArangoDB service
      ansible.builtin.service:
        name: arangodb3
        state: restarted

    - name: Wait for ArangoDB after restart
      ansible.builtin.wait_for:
        host: 127.0.0.1
        port: 8529
        delay: 3
        timeout: 240

    - name: Set ArangoDB root password (only if provided)
      ansible.builtin.shell: |
        set -euo pipefail
        arangosh \
          --server.endpoint tcp://127.0.0.1:8529 \
          --javascript.execute-string "require('@arangodb/users').update('root', '{{ root_password }}');"
      args:
        executable: /bin/bash
      when: root_password != ""

    - name: Proceed with database setup if credentials are provided
      block:
        - name: Create ArangoDB database
          ansible.builtin.shell: |
            set -euo pipefail
            arangosh \
              --server.endpoint tcp://127.0.0.1:8529 \
              --server.username root \
              --server.password '{{ root_password }}' \
              --javascript.execute-string "db._createDatabase('{{ db_name }}');"
          args:
            executable: /bin/bash

        - name: Create ArangoDB user
          ansible.builtin.shell: |
            set -euo pipefail
            arangosh \
              --server.endpoint tcp://127.0.0.1:8529 \
              --server.username root \
              --server.password '{{ root_password }}' \
              --javascript.execute-string "require('@arangodb/users').save('{{ db_user }}', '{{ db_password }}');"
          args:
            executable: /bin/bash

        - name: Grant user access to database
          ansible.builtin.shell: |
            set -euo pipefail
            arangosh \
              --server.endpoint tcp://127.0.0.1:8529 \
              --server.username root \
              --server.password '{{ root_password }}' \
              --javascript.execute-string "require('@arangodb/users').grantDatabase('{{ db_user }}', '{{ db_name }}');"
          args:
            executable: /bin/bash
      when:
        - db_name != ''
        - db_user != ''
        - db_password != ''
        - root_password != ''

    - name: Skip database setup if credentials are not provided
      ansible.builtin.debug:
        msg: "Database credentials not provided; skipping database and user creation."
      when:
        - db_name == '' or db_user == '' or db_password == '' or root_password == ''
