---
- name: Install and Configure ArangoDB (Ubuntu - Morpheus, debug-friendly)
  hosts: all
  become: yes
  gather_facts: yes

  vars:
    db_password: "{{ hostvars[inventory_hostname]['morpheus']['customOptions']['dbCustomPassword'] | default('') }}"
    db_user: "{{ hostvars[inventory_hostname]['morpheus']['customOptions']['dbCustomUser'] | default('') }}"
    db_name: "{{ hostvars[inventory_hostname]['morpheus']['customOptions']['dbCustomName'] | default('') }}"
    root_password: "{{ hostvars[inventory_hostname]['morpheus']['customOptions']['dbCustomPassword'] | default('') }}"

    arangodb_repo_base: "https://download.arangodb.com/arangodb312/DEBIAN"
    arangodb_key_url: "https://download.arangodb.com/arangodb312/DEBIAN/Release.key"
    arangodb_keyring_path: "/usr/share/keyrings/arangodb.gpg"
    arangodb_repo_line: "deb [signed-by={{ arangodb_keyring_path }}] {{ arangodb_repo_base }}/ /"

  environment:
    DEBIAN_FRONTEND: noninteractive

  tasks:
    - name: Fail if not Ubuntu
      ansible.builtin.fail:
        msg: "This playbook is intended for Ubuntu. Detected: {{ ansible_distribution }} {{ ansible_distribution_version }}"
      when: ansible_distribution != "Ubuntu"

    - name: Install prerequisites (curl, gnupg, ca-certificates)
      ansible.builtin.apt:
        name:
          - ca-certificates
          - curl
          - gnupg
        state: present
        update_cache: yes

    - name: Create ArangoDB keyring using curl (bypass Python HTTPS)
      ansible.builtin.shell: |
        set -euo pipefail
        curl -fsSL "{{ arangodb_key_url }}" | gpg --dearmor -o "{{ arangodb_keyring_path }}"
        chmod 0644 "{{ arangodb_keyring_path }}"
      args:
        executable: /bin/bash
        creates: "{{ arangodb_keyring_path }}"

    - name: Add ArangoDB repository (signed-by keyring)
      ansible.builtin.apt_repository:
        repo: "{{ arangodb_repo_line }}"
        state: present
        filename: arangodb

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install ArangoDB
      ansible.builtin.apt:
        name: arangodb3
        state: present

    # Force bind endpoint explicitly (prevents “not listening on localhost” situations)
    - name: Ensure ArangoDB endpoint is localhost:8529
      ansible.builtin.lineinfile:
        path: /etc/arangodb3/arangod.conf
        regexp: '^#?\s*endpoint\s*='
        line: 'endpoint = tcp://127.0.0.1:8529'
        insertafter: '^\[server\]'

    - name: Enable authentication in ArangoDB configuration
      ansible.builtin.lineinfile:
        path: /etc/arangodb3/arangod.conf
        regexp: '^#?\s*authentication\s*='
        line: 'authentication = true'
        insertafter: '^\[server\]'

    - name: Reload systemd
      ansible.builtin.command: systemctl daemon-reload
      changed_when: false

    - name: Enable and start ArangoDB service
      ansible.builtin.service:
        name: arangodb3
        state: started
        enabled: yes

    # If service didn't start, FAIL with journal (so you see the real reason in Morpheus output)
    - name: Check arangodb3 is active
      ansible.builtin.command: systemctl is-active arangodb3
      register: arango_active
      changed_when: false
      failed_when: false

    - name: Dump arangodb3 status + journal if not active
      ansible.builtin.shell: |
        set +e
        echo "=== systemctl status arangodb3 ==="
        systemctl status arangodb3 --no-pager -l
        echo
        echo "=== journalctl -u arangodb3 (last 250 lines) ==="
        journalctl -u arangodb3 --no-pager -n 250
        echo
        echo "=== ss -tulnp | grep 8529/arangod ==="
        ss -tulnp | grep -E '(:8529\b|arangod)' || true
        echo
        echo "=== arangod.conf key lines ==="
        grep -nE '^\[server\]|^endpoint|^authentication|^#?authentication' /etc/arangodb3/arangod.conf || true
      args:
        executable: /bin/bash
      register: arango_debug
      changed_when: false
      when: arango_active.stdout != "active"

    - name: Fail with ArangoDB startup logs
      ansible.builtin.fail:
        msg: |
          ArangoDB service is not active.
          Output:
          {{ arango_debug.stdout }}
      when: arango_active.stdout != "active"

    - name: Wait for ArangoDB to be ready on 127.0.0.1:8529
      ansible.builtin.wait_for:
        host: 127.0.0.1
        port: 8529
        delay: 3
        timeout: 60

    - name: Set ArangoDB root password (only if provided)
      ansible.builtin.shell: |
        set -euo pipefail
        arangosh \
          --server.endpoint tcp://127.0.0.1:8529 \
          --javascript.execute-string "require('@arangodb/users').update('root', '{{ root_password }}');"
      args:
        executable: /bin/bash
      when: root_password != ""

    - name: Proceed with database setup if credentials are provided
      block:
        - name: Create ArangoDB database
          ansible.builtin.shell: |
            set -euo pipefail
            arangosh \
              --server.endpoint tcp://127.0.0.1:8529 \
              --server.username root \
              --server.password '{{ root_password }}' \
              --javascript.execute-string "db._createDatabase('{{ db_name }}');"
          args:
            executable: /bin/bash

        - name: Create ArangoDB user
          ansible.builtin.shell: |
            set -euo pipefail
            arangosh \
              --server.endpoint tcp://127.0.0.1:8529 \
              --server.username root \
              --server.password '{{ root_password }}' \
              --javascript.execute-string "require('@arangodb/users').save('{{ db_user }}', '{{ db_password }}');"
          args:
            executable: /bin/bash

        - name: Grant user access to database
          ansible.builtin.shell: |
            set -euo pipefail
            arangosh \
              --server.endpoint tcp://127.0.0.1:8529 \
              --server.username root \
              --server.password '{{ root_password }}' \
              --javascript.execute-string "require('@arangodb/users').grantDatabase('{{ db_user }}', '{{ db_name }}');"
          args:
            executable: /bin/bash
      when:
        - db_name != ''
        - db_user != ''
        - db_password != ''
        - root_password != ''

    - name: Skip database setup if credentials are not provided
      ansible.builtin.debug:
        msg: "Database credentials not provided; skipping database and user creation."
      when:
        - db_name == '' or db_user == '' or db_password == '' or root_password == ''
