---
- name: Install Coolify 
  hosts: all
  become: true
  gather_facts: yes

  vars:
    coolify_port: 8000

  tasks:
    # -----------------------
    # Install basic deps
    # -----------------------
    - name: Install dependencies
      apt:
        name:
          - curl
          - ca-certificates
          - gnupg
          - lsb-release
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"

    # -----------------------
    # Docker install 
    # -----------------------
    - name: Check if Docker exists
      stat:
        path: /usr/bin/docker
      register: docker_bin

    - name: Install Docker if missing
      shell: curl -fsSL https://get.docker.com | sh
      when: not docker_bin.stat.exists

    - name: Ensure Docker is running
      systemd:
        name: docker
        state: started
        enabled: yes

    # -----------------------
    # Add SSH user to docker group
    # -----------------------
    - name: Get remote SSH user
      set_fact:
        real_user: "{{ ansible_env.SUDO_USER | default(ansible_env.USER) }}"

    - name: Add user to docker group
      user:
        name: "{{ real_user }}"
        groups: docker
        append: yes

    # -----------------------
    # Install Coolify
    # -----------------------
    - name: Install Coolify (non-interactive)
      shell: |
        export COOLIFY_NON_INTERACTIVE=true
        curl -fsSL https://cdn.coollabs.io/coolify/install.sh | bash
      args:
        executable: /bin/bash

    # -----------------------
    # Wait for any Coolify container to start
    # -----------------------
    - name: Wait for Coolify container to appear
      shell: docker ps --format '{{"{{.Names}}"}}' | grep coolify
      register: coolify_check
      retries: 20        
      delay: 15
      until: coolify_check.stdout != ""

    # -----------------------
    # Final message
    # -----------------------
    - name: Coolify installed
      debug:
        msg: "✅ Coolify is running. Access it on port {{ coolify_port }}"


