- name: Install Coolify (Minimal & Robust)
  hosts: all
  become: true
  vars:
    coolify_port: 8000

  tasks:
    # Install Docker if missing
    - name: Check if Docker is installed
      stat:
        path: /usr/bin/docker
      register: docker_check

    - name: Install Docker if missing
      shell: curl -fsSL https://get.docker.com | sh
      when: not docker_check.stat.exists
      retries: 2

    # Start Docker (ALWAYS needed)
    - name: Ensure Docker is running
      systemd:
        name: docker
        state: started
        enabled: yes

    # Add user to group if needed
    - name: Check Docker group membership
      shell: id -nG "{{ ansible_user }}" | grep -q docker && echo "in_group" || echo "not_in_group"
      register: group_check
      changed_when: false

    - name: Add to Docker group if needed
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes
      when: "'in_group' not in group_check.stdout"

    # Run installer (idempotent - checks if already installed)
    - name: Check if Coolify is already running
      shell: |
        docker ps --filter "name=coolify" --quiet | head -1
      register: coolify_check
      changed_when: false

    - name: Install Coolify if not present
      shell: |
        curl -fsSL https://cdn.coollabs.io/coolify/install.sh | bash -s -- --non-interactive
      when: coolify_check.stdout == ""
      async: 1800
      poll: 30

    # Verify
    - name: Verify Coolify is accessible
      wait_for:
        port: "{{ coolify_port }}"
        timeout: 120
      when: coolify_check.stdout == ""
