---
- name: Install Coolify
  hosts: all
  become: true
  vars:
    coolify_port: 8000
    coolify_dir: /coolify

  tasks:
    # -----------------------
    # DNS Configuration
    # -----------------------
    - name: Configure DNS (Ubuntu)
      when: ansible_distribution == "Ubuntu"
      copy:
        dest: /etc/resolv.conf
        content: |
          nameserver 8.8.8.8
          nameserver 8.8.4.4

    - name: Clear apt proxy (Ubuntu)
      when: ansible_distribution == "Ubuntu"
      file:
        path: /etc/apt/apt.conf.d/90curtin-aptproxy
        state: absent

    - name: Update apt cache (Ubuntu)
      when: ansible_distribution == "Ubuntu"
      apt:
        update_cache: yes
        cache_valid_time: 3600

    # -----------------------
    # Install dependencies
    # -----------------------
    - name: Install dependencies (Ubuntu)
      when: ansible_distribution == "Ubuntu"
      apt:
        name:
          - curl
          - wget
          - git
          - jq
          - openssl
        state: present

    # -----------------------
    # Install Docker
    # -----------------------
    - name: Install Docker via official script (Ubuntu)
      when: ansible_distribution == "Ubuntu"
      shell: curl -fsSL https://get.docker.com | sh
      args:
        creates: /usr/bin/docker

    - name: Start and enable Docker
      systemd:
        name: docker
        state: started
        enabled: yes

    # -----------------------
    # Docker permissions fix
    # -----------------------
    - name: Add playbook user to Docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    # -----------------------
    # Coolify directories
    # -----------------------
    - name: Create Coolify directories
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - "{{ coolify_dir }}"
        - "{{ coolify_dir }}/data"

    # -----------------------
    # Pre-pull required Docker images
    # -----------------------
    - name: Pull Coolify helper image
      docker_image:
        name: ghcr.io/coollabsio/coolify-helper
        tag: 1.0.12
        source: pull

    - name: Pull main Coolify image
      docker_image:
        name: ghcr.io/coollabsio/coolify
        tag: latest
        source: pull

    # -----------------------
    # Download Coolify install script
    # -----------------------
    - name: Download Coolify install script
      shell: curl -fsSL https://cdn.coollabs.io/coolify/install.sh -o /tmp/coolify_install.sh
      args:
        creates: /tmp/coolify_install.sh
        executable: /bin/bash

    - name: Set execute permission on install script
      file:
        path: /tmp/coolify_install.sh
        mode: '0755'

    # -----------------------
    # Execute Coolify installation
    # -----------------------
    - name: Execute Coolify install script
      shell: bash /tmp/coolify_install.sh --non-interactive
      args:
        executable: /bin/bash
      async: 1800
      poll: 30

    # -----------------------
    # Wait for Coolify to be ready
    # -----------------------
    - name: Wait for Coolify to be available
      wait_for:
        port: "{{ coolify_port }}"
        timeout: 300
        delay: 10

    - name: Installation complete
      debug:
        msg: "Coolify installed successfully. Access it at https://{{ morpheus['server']['internalIp'] | default('127.0.0.1') }}:{{ coolify_port }}"
