---
- name: Install Coolify on Ubuntu 24.04
  hosts: all
  become: true
  gather_facts: yes

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install Docker dependencies
      apt:
        name:
          - docker.io
          - curl
          - git
          - jq
        state: present

    - name: Start and enable Docker service
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Install Docker Compose (official binary)
      get_url:
        url: https://github.com/docker/compose/releases/download/v2.23.1/docker-compose-linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: '0755'

    - name: Ensure docker-compose is executable
      file:
        path: /usr/local/bin/docker-compose
        mode: '0755'

    - name: Verify Docker Compose installation
      command: docker-compose --version
      register: compose_check

    - name: Download Coolify installer
      get_url:
        url: https://cdn.coollabs.io/coolify/install.sh
        dest: /tmp/install-coolify.sh
        mode: '0755'

    - name: Install Coolify (non-interactive)
      command: /tmp/install-coolify.sh --non-interactive
      async: 900  # 15 minutes
      poll: 15

    - name: Wait for Coolify to be available
      wait_for:
        port: 8000
        delay: 30
        timeout: 300

    - name: Show Coolify access info
      debug:
        msg: "Coolify installed! Access it at http://{{ ansible_default_ipv4.address }}:8000"
