---
- name: Install Coolify (Robust & Idempotent)
  hosts: all
  become: true
  gather_facts: yes

  vars:
    coolify_port: 8000
    coolify_dir: /data/coolify

  tasks:

    # -----------------------
    # System dependencies
    # -----------------------
    - name: Install dependencies
      apt:
        name:
          - curl
          - ca-certificates
          - gnupg
          - lsb-release
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"

    # -----------------------
    # Docker install
    # -----------------------
    - name: Check if Docker exists
      stat:
        path: /usr/bin/docker
      register: docker_bin

    - name: Install Docker if missing
      shell: curl -fsSL https://get.docker.com | sh
      when: not docker_bin.stat.exists

    - name: Ensure Docker is running
      systemd:
        name: docker
        state: started
        enabled: yes

    # -----------------------
    # Install docker-compose plugin
    # -----------------------
    - name: Install docker-compose plugin
      apt:
        name: docker-compose-plugin
        state: present
        update_cache: yes

    # -----------------------
    # Install Coolify ONLY if not installed
    # -----------------------
    - name: Check if Coolify already installed
      stat:
        path: "{{ coolify_dir }}/docker-compose.yml"
      register: coolify_compose

    - name: Download Coolify installer
      get_url:
        url: https://cdn.coollabs.io/coolify/install.sh
        dest: /tmp/coolify.sh
        mode: '0755'
      when: not coolify_compose.stat.exists

    - name: Run Coolify installer (non-interactive)
      shell: |
        export COOLIFY_NON_INTERACTIVE=true
        /tmp/coolify.sh
      args:
        executable: /bin/bash
      when: not coolify_compose.stat.exists

    # -----------------------
    # Ensure Coolify containers are running
    # -----------------------
    - name: Start Coolify containers
      shell: |
        cd {{ coolify_dir }}
        docker compose up -d
      args:
        executable: /bin/bash

    # -----------------------
    # Verify Coolify containers
    # -----------------------
    - name: Verify Coolify containers
      shell: docker ps --format "{{ '{{' }}.Names{{ '}}' }}"
      register: running_containers

    - name: Fail if Coolify is not running
      fail:
        msg: "❌ Coolify containers are NOT running"
      when: "'coolify' not in running_containers.stdout"

    # -----------------------
    # Success message
    # -----------------------
    - name: Coolify installed successfully
      debug:
        msg: |
          ✅ COOLIFY INSTALLED AND RUNNING
          Access URL:
          http://{{ ansible_default_ipv4.address }}:{{ coolify_port }}

          


