  GNU nano 7.2                                                                                                                                                                                                                     coolify.yml                                                                                                                                                                                                                              
---
- name: Install Coolify (Robust – Morpheus & Ubuntu)
  hosts: all
  become: true
  gather_facts: yes

  vars:
    coolify_port: 8000

  tasks:
    # -----------------------
    # Install basic deps
    # -----------------------
    - name: Install dependencies
      apt:
        name:
          - curl
          - ca-certificates
          - gnupg
          - lsb-release
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"

    # -----------------------
    # Docker install (safe)
    # -----------------------
    - name: Check if Docker exists
      stat:
        path: /usr/bin/docker
      register: docker_bin

    - name: Install Docker if missing
      shell: curl -fsSL https://get.docker.com | sh
      when: not docker_bin.stat.exists

    - name: Ensure Docker is running
      systemd:
        name: docker
        state: started
        enabled: yes

    # -----------------------
    # Add SSH user to docker group
    # -----------------------
    - name: Get remote SSH user
      set_fact:
        real_user: "{{ ansible_env.SUDO_USER | default(ansible_env.USER) }}"

    - name: Add user to docker group
      user:
        name: "{{ real_user }}"
        groups: docker
        append: yes

    # -----------------------
    # Install Coolify (CORRECT WAY)
    # -----------------------
    - name: Install Coolify (non-interactive FIXED)
      shell: |
        export COOLIFY_NON_INTERACTIVE=true
        curl -fsSL https://cdn.coollabs.io/coolify/install.sh | bash
      args:
        executable: /bin/bash
      async: 1800
      poll: 30
      register: coolify_install
      failed_when: false

    # -----------------------
    # Verify Coolify really started
    # -----------------------
    - name: Wait for Coolify container
      shell: docker ps --format '{{ "{{" }}.Names{{ "}}" }}' | grep -q coolify
      register: coolify_check
      retries: 12
      delay: 10
      until: coolify_check.rc == 0

    # -----------------------
    # Final message
    # -----------------------
    - name: Coolify installed
      debug:
        msg: "✅ Coolify is running. Access it on port {{ coolify_port }}"

