---
- name: Install Coolify 
  hosts: all
  become: true
  gather_facts: yes

  vars:
    coolify_port: 8000

  tasks:
    # -----------------------
    # Basic dependencies
    # -----------------------
    - name: Install dependencies
      apt:
        name:
          - curl
          - ca-certificates
          - gnupg
          - lsb-release
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"

    # -----------------------
    # Docker install
    # -----------------------
    - name: Check if Docker exists
      stat:
        path: /usr/bin/docker
      register: docker_bin

    - name: Install Docker if missing
      shell: curl -fsSL https://get.docker.com | sh
      when: not docker_bin.stat.exists
      args:
        executable: /bin/bash

    - name: Ensure Docker is running
      systemd:
        name: docker
        state: started
        enabled: yes

    # -----------------------
    # Docker group access
    # -----------------------
    - name: Detect real SSH user
      set_fact:
        real_user: "{{ ansible_env.SUDO_USER | default(ansible_env.USER) }}"

    - name: Add user to docker group
      user:
        name: "{{ real_user }}"
        groups: docker
        append: yes

    # -----------------------
    # Coolify install (FIXED)
    # -----------------------
    - name: Download Coolify installer (curl workaround)
      shell: |
        curl -fsSL https://cdn.coollabs.io/coolify/install.sh -o /tmp/coolify.sh
        chmod +x /tmp/coolify.sh
      args:
        executable: /bin/bash

    - name: Install Coolify (non-interactive)
      shell: |
        export COOLIFY_NON_INTERACTIVE=true
        /tmp/coolify.sh
      args:
        executable: /bin/bash
      register: coolify_install
      failed_when: false

    # -----------------------
    # Verification
    # -----------------------
    - name: Wait for Docker containers
      shell: sleep 15

    - name: Check Coolify data directory
      stat:
        path: /data/coolify
      register: coolify_dir

    - name: List running containers
      shell: docker ps
      register: docker_ps

    # -----------------------
    # Final output
    # -----------------------
    - name: Coolify installation status
      debug:
        msg: |
          ✅ COOLIFY INSTALLATION FINISHED

          Data directory exists: {{ coolify_dir.stat.exists }}

          Running containers:
          {{ docker_ps.stdout }}

          Access Coolify at:
          http://{{ ansible_default_ipv4.address | default('localhost') }}:{{ coolify_port }}


          


