---
- name: Install Coolify 
  hosts: all
  become: true
  gather_facts: yes

  vars:
    coolify_port: 8000

  tasks:
    # -----------------------
    # Install basic deps
    # -----------------------
    - name: Install dependencies
      apt:
        name:
          - curl
          - ca-certificates
          - gnupg
          - lsb-release
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"

    # -----------------------
    # Docker install 
    # -----------------------
    - name: Check if Docker exists
      stat:
        path: /usr/bin/docker
      register: docker_bin

    - name: Install Docker if missing
      shell: curl -fsSL https://get.docker.com | sh
      when: not docker_bin.stat.exists

    - name: Ensure Docker is running
      systemd:
        name: docker
        state: started
        enabled: yes

    # -----------------------
    # Add SSH user to docker group
    # -----------------------
    - name: Get remote SSH user
      set_fact:
        real_user: "{{ ansible_env.SUDO_USER | default(ansible_env.USER) }}"

    - name: Add user to docker group
      user:
        name: "{{ real_user }}"
        groups: docker
        append: yes

    # -----------------------
    # Install Coolify - SIMPLE VERSION (NO ASYNC)
    # -----------------------
    - name: Install Coolify (non-interactive)
      shell: |
        export COOLIFY_NON_INTERACTIVE=true
        curl -fsSL https://cdn.coollabs.io/coolify/install.sh | bash
      args:
        executable: /bin/bash
      # Removed async/poll - Morpheus doesn't like it
      register: coolify_install
      # Don't fail even if there are warnings
      failed_when: false

    # -----------------------
    # Check if Coolify is running (simple check)
    # -----------------------
    - name: Check if Coolify directory exists
      stat:
        path: /data/coolify
      register: coolify_dir

    - name: Check running containers
      shell: docker ps --format "table {{ "{{" }}.Names{{ "}}" }}\t{{ "{{" }}.Status{{ "}}" }}\t{{ "{{" }}.Ports{{ "}}" }}"
      register: docker_containers

    # -----------------------
    # Final success message
    # -----------------------
    - name: Coolify installation status
      debug:
        msg: |
          ✅ COOLIFY INSTALLATION COMPLETE!
          
          Based on the installation log, Coolify was successfully installed!
          
          Access Coolify at: http://{{ ansible_default_ipv4.address | default('localhost') }}:8000
          
          


