---
- name: Install Elasticsearch Stack
  hosts: all
  become: true
  vars:
    elastic_version: "8.x"

  tasks:
    # Ubuntu-specific tasks
    - name: Install required packages (Ubuntu)
      when: ansible_distribution == "Ubuntu"
      apt:
        name:
          - apt-transport-https
          - curl
          - gnupg
          - ca-certificates
        state: present
        update_cache: yes

    - name: Add Elasticsearch GPG key (Ubuntu)
      when: ansible_distribution == "Ubuntu"
      ansible.builtin.apt_key:
        url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
        state: present

    - name: Add Elasticsearch repository (Ubuntu)
      when: ansible_distribution == "Ubuntu"
      ansible.builtin.apt_repository:
        repo: "deb https://artifacts.elastic.co/packages/{{ elastic_version }}/apt stable main"
        state: present
        filename: "elastic-{{ elastic_version }}"

    - name: Update apt cache (Ubuntu)
      when: ansible_distribution == "Ubuntu"
      apt:
        update_cache: yes

    # Common installation tasks
    - name: Install Elasticsearch, Kibana, Logstash
      package:
        name:
          - elasticsearch
          - kibana
          - logstash
        state: present

    - name: Configure Kibana to listen on all interfaces
      lineinfile:
        path: /etc/kibana/kibana.yml
        regexp: '^server\.host:'
        line: 'server.host: "0.0.0.0"'
        create: yes

    - name: Ensure systemd override directory exists for Elasticsearch
      file:
        path: /etc/systemd/system/elasticsearch.service.d
        state: directory
        mode: '0755'

    - name: Configure Elasticsearch service with proxy
      copy:
        content: |
          [Service]
          Environment="NO_PROXY=localhost,127.0.0.1"
        dest: /etc/systemd/system/elasticsearch.service.d/http-proxy.conf
        mode: '0644'

    - name: Reload systemd daemon
      systemd:
        daemon_reload: yes

    - name: Start and enable Elasticsearch, Kibana, Logstash
      systemd:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop:
        - elasticsearch
        - kibana
        - logstash

    - name: Wait for Elasticsearch to start
      wait_for:
        port: 9200
        delay: 10
        timeout: 300

    - name: Generate Elastic password
      shell: "/usr/share/elasticsearch/bin/elasticsearch-reset-password -u elastic --batch"
      register: elastic_password
      changed_when: false

    - name: Generate Kibana enrollment token
      shell: "/usr/share/elasticsearch/bin/elasticsearch-create-enrollment-token -s kibana"
      register: kibana_token
      changed_when: false

    - name: Display Elastic password
      debug:
        var: elastic_password.stdout_lines

    - name: Display Kibana enrollment token
      debug:
        var: kibana_token.stdout_lines

    - name: Print installation complete message
      debug:
        msg: "Elasticsearch Stack has been installed successfully. Access Kibana at https://{{ ansible_host }}:5601"
