- name: Install ELK Stack 8.x on Ubuntu 24.04 
  hosts: all
  become: true

  vars:
    elastic_major: "8"

  tasks:

    - name: Remove apt proxy if present
      file:
        path: /etc/apt/apt.conf.d/90curtin-aptproxy
        state: absent

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install base dependencies
      apt:
        name:
          - ca-certificates
          - curl
          - gnupg
          - apt-transport-https
        state: present

    - name: Download Elasticsearch GPG key
      shell: |
        curl -fsSL https://artifacts.elastic.co/GPG-KEY-elasticsearch \
        | gpg --dearmor -o /usr/share/keyrings/elasticsearch-keyring.gpg
      args:
        creates: /usr/share/keyrings/elasticsearch-keyring.gpg

    - name: Add Elasticsearch repository
      apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/elasticsearch-keyring.gpg] https://artifacts.elastic.co/packages/{{ elastic_major }}.x/apt stable main"
        filename: elasticsearch
        state: present

    - name: Update apt cache after Elastic repo
      apt:
        update_cache: yes

    - name: Install Elasticsearch
      apt:
        name: elasticsearch
        state: present

    # Disable HTTPS for HTTP traffic ***************************************************
    - name: Disable HTTPS for HTTP traffic in elasticsearch.yml
      lineinfile:
        path: /etc/elasticsearch/elasticsearch.yml
        regexp: '^xpack.security.http.ssl.enabled:'
        line: 'xpack.security.http.ssl.enabled: false'
        create: yes
      notify:
        - Restart Elasticsearch

    - name: Enable and start Elasticsearch
      systemd:
        name: elasticsearch
        state: started
        enabled: yes

    - name: Wait for Elasticsearch
      wait_for:
        port: 9200
        timeout: 300

    - name: Install Kibana
      apt:
        name: kibana
        state: present

    - name: Configure Kibana to listen on all interfaces
      lineinfile:
        path: /etc/kibana/kibana.yml
        regexp: '^server.host:'
        line: 'server.host: "0.0.0.0"'
        create: yes

    - name: Enable and start Kibana
      systemd:
        name: kibana
        state: started
        enabled: yes

    - name: Install Logstash
      apt:
        name: logstash
        state: present

    - name: Enable and start Logstash
      systemd:
        name: logstash
        state: started
        enabled: yes

    - name: Reset elastic password
      command: /usr/share/elasticsearch/bin/elasticsearch-reset-password -u elastic --batch
      register: elastic_password
      changed_when: false

    - name: Create Kibana enrollment token
      command: /usr/share/elasticsearch/bin/elasticsearch-create-enrollment-token -s kibana
      register: kibana_token
      changed_when: false

    - name: Show elastic password
      debug:
        msg: "{{ elastic_password.stdout }}"

    - name: Show Kibana enrollment token
      debug:
        msg: "{{ kibana_token.stdout }}"

  handlers:
    - name: Restart Elasticsearch
      systemd:
        name: elasticsearch
        state: restarted

