---
- name: Install Elastic Stack on Ubuntu 24.04
  hosts: all
  become: true
  vars:
    elastic_version: "8.x"
    # Sécurité: par défaut localhost seulement
    kibana_host: "localhost"
    # Option pour exposition externe si nécessaire
    expose_kibana: true #true écoute sur 0.0.0.0 $$$$$$ >>>> false ? : écoute sur localhost  

  tasks:
    # Nettoyage DNS (optionnel, mieux de garder DHCP)
    - name: Backup current resolv.conf
      copy:
        src: /etc/resolv.conf
        dest: /etc/resolv.conf.backup
        remote_src: true
      when: ansible_distribution == "Ubuntu"

    # Installation des prérequis Ubuntu
    - name: Install required packages for Ubuntu
      when: ansible_distribution == "Ubuntu"
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present
        update_cache: yes

    # Setup repository Elasticsearch (méthode officielle)
    - name: Setup Elasticsearch GPG key
      when: ansible_distribution == "Ubuntu"
      apt_key:
        url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
        state: present

    - name: Add Elasticsearch repository
      when: ansible_distribution == "Ubuntu"
      apt_repository:
        repo: "deb https://artifacts.elastic.co/packages/{{ elastic_version }}/apt stable main"
        filename: elasticsearch
        state: present
        update_cache: yes

    # Install Java 17 (requis pour Elasticsearch 8.x)
    - name: Install OpenJDK 17
      when: ansible_distribution == "Ubuntu"
      apt:
        name: openjdk-17-jdk-headless
        state: present

    # Installation des composants Elastic
    - name: Install Elasticsearch
      apt:
        name: elasticsearch
        state: present

    - name: Install Kibana
      apt:
        name: kibana
        state: present
      when: install_kibana | default(true)

    - name: Install Logstash (optionnel)
      apt:
        name: logstash
        state: present
      when: install_logstash | default(false)

    # Configuration Elasticsearch
    - name: Configure Elasticsearch basic settings
      lineinfile:
        path: /etc/elasticsearch/elasticsearch.yml
        regexp: '^#network.host:'
        line: 'network.host: 0.0.0.0'
      notify: restart elasticsearch

    # Configuration Kibana (plus sécurisée)
    - name: Configure Kibana host
      lineinfile:
        path: /etc/kibana/kibana.yml
        regexp: '^#?server.host:'
        line: 'server.host: "{{ kibana_host if expose_kibana else "localhost" }}"'
        create: yes
      when: install_kibana | default(true)
      notify: restart kibana

    - name: Configure Kibana to connect to Elasticsearch
      lineinfile:
        path: /etc/kibana/kibana.yml
        regexp: '^#?elasticsearch.hosts:'
        line: 'elasticsearch.hosts: ["http://localhost:9200"]'
        create: yes
      when: install_kibana | default(true)
      notify: restart kibana

    # Démarrer les services
    - name: Enable and start Elasticsearch
      systemd:
        name: elasticsearch
        enabled: yes
        state: started
        daemon_reload: yes

    - name: Enable and start Kibana
      systemd:
        name: kibana
        enabled: yes
        state: started
      when: install_kibana | default(true)

    - name: Enable and start Logstash
      systemd:
        name: logstash
        enabled: yes
        state: started
      when: install_logstash | default(false)

    # Sécurité: configuration initiale
    - name: Wait for Elasticsearch to be ready
      wait_for:
        port: 9200
        delay: 15
        timeout: 120

    - name: Get initial elastic password
      shell: |
        if [ -f /usr/share/elasticsearch/config/elasticsearch.keystore ]; then
          /usr/share/elasticsearch/bin/elasticsearch-reset-password -u elastic -b 2>/dev/null || echo "password_not_available_yet"
        else
          echo "setup_required"
        fi
      register: elastic_password
      changed_when: false

    - name: Display connection information
      debug:
        msg: |
          🎉 Elastic Stack installé sur Ubuntu 24.04!
          
          Elasticsearch: http://localhost:9200
          Kibana: http://localhost:5601
          
         

  handlers:
    - name: restart elasticsearch
      systemd:
        name: elasticsearch
        state: restarted

    - name: restart kibana
      systemd:
        name: kibana
        state: restarted

    - name: restart logstash
      systemd:
        name: logstash
        state: restarted
