- name: Install Jenkins on Ubuntu 24.04 
  hosts: all
  become: true

  tasks:

    - name: Remove apt proxy if present
      file:
        path: /etc/apt/apt.conf.d/90curtin-aptproxy
        state: absent

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install base packages
      apt:
        name:
          - ca-certificates
          - curl
          - gnupg
        state: present

    - name: Install Java 17
      apt:
        name: openjdk-17-jdk
        state: present

    - name: Download Jenkins GPG key (curl – Morpheus safe)
      shell: |
        curl -fsSL https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key \
        -o /usr/share/keyrings/jenkins-keyring.asc
      args:
        creates: /usr/share/keyrings/jenkins-keyring.asc

    - name: Add Jenkins repository
      apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/"
        filename: jenkins
        state: present

    - name: Update apt cache after adding Jenkins repo
      apt:
        update_cache: yes

    - name: Install Jenkins
      apt:
        name: jenkins
        state: present

    - name: Enable and start Jenkins
      systemd:
        name: jenkins
        state: started
        enabled: yes

    - name: Wait for Jenkins to listen on port 8080
      wait_for:
        port: 8080
        timeout: 300

    - name: Read initial Jenkins admin password
      command: cat /var/lib/jenkins/secrets/initialAdminPassword
      register: jenkins_password
      changed_when: false

    - name: Display Jenkins admin password
      debug:
        msg: "Jenkins admin password: {{ jenkins_password.stdout }}"


