---
- name: Install and Configure MariaDB (Ubuntu)
  hosts: all
  become: true
  gather_facts: true

  vars:
    # Morpheus options (fallbacks included)
    mariadb_admin_password: "{{ hostvars[inventory_hostname]['morpheus']['customOptions']['dbCustomPassword'] | default('rootroot') }}"
    db_password: "{{ hostvars[inventory_hostname]['morpheus']['customOptions']['dbCustomPassword'] | default('') }}"
    db_user: "{{ hostvars[inventory_hostname]['morpheus']['customOptions']['dbCustomUser'] | default('') }}"
    db_name: "{{ hostvars[inventory_hostname]['morpheus']['customOptions']['dbCustomName'] | default('') }}"
    ansible_remote_tmp: "/var/tmp/.ansible/tmp"

  tasks:
    # -----------------------------
    # Guard: run only on Ubuntu (adjust if you want Debian too)
    # -----------------------------
    - name: Fail if not Ubuntu (this playbook is Ubuntu-focused)
      when: ansible_distribution != "Ubuntu"
      fail:
        msg: "This MariaDB playbook currently supports Ubuntu only. Detected: {{ ansible_distribution }}"

    # -----------------------------
    # Install MariaDB
    # -----------------------------
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    # Preseed so apt doesn't prompt
    - name: Preseed MariaDB root password (non-interactive)
      debconf:
        name: "mariadb-server"
        question: "{{ item.question }}"
        value: "{{ item.value }}"
        vtype: "password"
      loop:
        - { question: "mysql-server/root_password", value: "{{ mariadb_admin_password }}" }
        - { question: "mysql-server/root_password_again", value: "{{ mariadb_admin_password }}" }
      changed_when: false

    - name: Install MariaDB server + client
      apt:
        name:
          - mariadb-server
          - mariadb-client
        state: present

    - name: Ensure MariaDB is started and enabled
      systemd:
        name: mariadb
        state: started
        enabled: yes

    - name: Wait for MariaDB socket
      wait_for:
        path: /run/mysqld/mysqld.sock
        timeout: 60

    # -----------------------------
    # Enforce auth model:
    # root -> unix_socket (so sudo mariadb works)
    # admin -> password (for automation)
    # -----------------------------
    - name: Ensure root uses unix_socket plugin (Ubuntu best practice)
      command: >
        mariadb -NBe
        "UPDATE mysql.user
         SET plugin='unix_socket', authentication_string=''
         WHERE User='root' AND Host='localhost';
         FLUSH PRIVILEGES;"
      become: true
      changed_when: true

    - name: Verify root socket login works
      command: sudo mariadb -NBe "SELECT 1;"
      changed_when: false

    - name: Create admin user with password for automation
      command: >
        sudo mariadb -NBe
        "CREATE USER IF NOT EXISTS 'admin'@'localhost' IDENTIFIED BY '{{ mariadb_admin_password }}';
         GRANT ALL PRIVILEGES ON *.* TO 'admin'@'localhost' WITH GRANT OPTION;
         FLUSH PRIVILEGES;"
      changed_when: true

    # Optional: create DB and app user if Morpheus options provided
    - name: Create database if provided
      when: db_name | length > 0
      command: >
        sudo mariadb -NBe
        "CREATE DATABASE IF NOT EXISTS \`{{ db_name }}\`;"

    - name: Create app user and grant privileges if provided
      when: (db_user | length > 0) and (db_password | length > 0) and (db_name | length > 0)
      command: >
        sudo mariadb -NBe
        "CREATE USER IF NOT EXISTS '{{ db_user }}'@'localhost' IDENTIFIED BY '{{ db_password }}';
         GRANT ALL PRIVILEGES ON \`{{ db_name }}\`.* TO '{{ db_user }}'@'localhost';
         FLUSH PRIVILEGES;"

    # -----------------------------
    # Validation output
    # -----------------------------
    - name: Show MariaDB version
      command: mariadb --version
      register: mariadb_version
      changed_when: false

    - name: Print MariaDB version
      debug:
        var: mariadb_version.stdout

    - name: Print login hints
      debug:
        msg:
          - "Root login (socket): sudo mariadb"
          - "Admin login (password): mariadb -u admin -p  (password is dbCustomPassword or 'rootroot')"
