---
- name: Install and Configure MariaDB
  hosts: all
  become: true
  gather_facts: true

  vars:
    ansible_python_interpreter: /usr/bin/python3

    mysql_root_password: "{{ hostvars[inventory_hostname]['morpheus']['customOptions']['dbCustomPassword'] | default('rootroot') }}"
    db_password: "{{ hostvars[inventory_hostname]['morpheus']['customOptions']['dbCustomPassword'] | default('') }}"
    db_user: "{{ hostvars[inventory_hostname]['morpheus']['customOptions']['dbCustomUser'] | default('') }}"
    db_name: "{{ hostvars[inventory_hostname]['morpheus']['customOptions']['dbCustomName'] | default('') }}"

    rhel_username: "{{ hostvars[inventory_hostname]['morpheus']['customOptions']['rhelEmail'] | default('') }}"
    rhel_password: "{{ hostvars[inventory_hostname]['morpheus']['customOptions']['rhelPw'] | default('') }}"

    ansible_remote_tmp: "/var/tmp/.ansible/tmp"

  tasks:
    - name: Ensure Ansible remote tmp directory exists
      file:
        path: "{{ ansible_remote_tmp }}"
        state: directory
        mode: "1777"
        owner: root
        group: root

    - name: Determine if custom DB vars are provided
      set_fact:
        db_vars_provided: "{{ (db_password | length > 0) and (db_user | length > 0) and (db_name | length > 0) }}"

    # -----------------------------
    # Networking sanity
    # -----------------------------
    - name: Configure resolv.conf with Google DNS
      copy:
        dest: /etc/resolv.conf
        mode: "0644"
        content: |
          nameserver 8.8.8.8
          nameserver 8.8.4.4

    # -----------------------------
    # Ubuntu install (OFFICIAL REPO ONLY)
    # -----------------------------
    - name: Install prerequisites (Ubuntu)
      when: ansible_distribution == "Ubuntu"
      apt:
        name:
          - python3-pymysql
        state: present
        update_cache: yes

    - name: Install MariaDB (Ubuntu)
      when: ansible_distribution == "Ubuntu"
      apt:
        name:
          - mariadb-server
          - mariadb-client
        state: present

    # -----------------------------
    # RHEL install
    # -----------------------------
    - name: Register and subscribe RHEL system
      when: ansible_os_family == "RedHat"
      command: subscription-manager register --username {{ rhel_username }} --password {{ rhel_password }} --auto-attach
      register: subscription_result
      failed_when: subscription_result.rc != 0 and 'This system is already registered' not in subscription_result.stderr
      changed_when: subscription_result.rc == 0

    - name: Enable required RHEL repositories
      when: ansible_os_family == "RedHat"
      command: subscription-manager repos --enable rhel-{{ ansible_distribution_major_version }}-for-x86_64-appstream-rpms
      register: repo_result
      failed_when: repo_result.rc != 0 and 'already enabled' not in repo_result.stderr
      changed_when: repo_result.rc == 0

    - name: Install MariaDB server (RHEL)
      when: ansible_os_family == "RedHat"
      yum:
        name:
          - mariadb-server
          - python3-PyMySQL
        state: present

    # -----------------------------
    # Common configuration
    # -----------------------------
    - name: Enable and start MariaDB
      systemd:
        name: mariadb
        enabled: yes
        state: started

    - name: Wait for MariaDB to respond
      command: mysqladmin ping
      register: mariadb_ping
      retries: 15
      delay: 2
      until: mariadb_ping.rc == 0
      changed_when: false

    - name: Try setting root password (best effort)
      shell: |
        mysql --user=root --execute="ALTER USER 'root'@'localhost' IDENTIFIED BY '{{ mysql_root_password }}'; FLUSH PRIVILEGES;"
      register: set_root_pw
      failed_when: false
      changed_when: set_root_pw.rc == 0

    - name: Remove anonymous users
      shell: |
        mysql --user=root --password="{{ mysql_root_password }}" --execute="DELETE FROM mysql.user WHERE User=''; FLUSH PRIVILEGES;"
      changed_when: true

    - name: Remove test database
      shell: |
        mysql --user=root --password="{{ mysql_root_password }}" --execute="DROP DATABASE IF EXISTS test; DELETE FROM mysql.db WHERE Db='test' OR Db='test\\_%'; FLUSH PRIVILEGES;"
      changed_when: true

    - name: Create database (optional)
      when: db_vars_provided
      shell: |
        mysql --user=root --password="{{ mysql_root_password }}" --execute="CREATE DATABASE IF NOT EXISTS {{ db_name }};"
      changed_when: true

    - name: Create user + grant privileges (optional)
      when: db_vars_provided
      shell: |
        mysql --user=root --password="{{ mysql_root_password }}" --execute="CREATE USER IF NOT EXISTS '{{ db_user }}'@'%' IDENTIFIED BY '{{ db_password }}';
        GRANT ALL PRIVILEGES ON {{ db_name }}.* TO '{{ db_user }}'@'%';
        FLUSH PRIVILEGES;"
      changed_when: true

    - name: Validation - MariaDB version
      command: mysql --user=root --password={{ mysql_root_password }} -e "SELECT VERSION();"
      register: mariadb_version
      changed_when: false

    - name: Print status
      debug:
        msg: "MariaDB OK. {{ mariadb_version.stdout_lines | default([]) }}"
