---
- name: Install and Configure MariaDB
  hosts: all
  become: true
  gather_facts: true

  vars:
    # Pin interpreter to remove Ansible "discovered interpreter" warning
    ansible_python_interpreter: /usr/bin/python3

    # Morpheus inputs
    mysql_root_password: "{{ hostvars[inventory_hostname]['morpheus']['customOptions']['dbCustomPassword'] | default('rootroot') }}"
    db_password: "{{ hostvars[inventory_hostname]['morpheus']['customOptions']['dbCustomPassword'] | default('') }}"
    db_user: "{{ hostvars[inventory_hostname]['morpheus']['customOptions']['dbCustomUser'] | default('') }}"
    db_name: "{{ hostvars[inventory_hostname]['morpheus']['customOptions']['dbCustomName'] | default('') }}"

    rhel_username: "{{ hostvars[inventory_hostname]['morpheus']['customOptions']['rhelEmail'] | default('') }}"
    rhel_password: "{{ hostvars[inventory_hostname]['morpheus']['customOptions']['rhelPw'] | default('') }}"

    # Safer tmp for some locked-down images
    ansible_remote_tmp: "/var/tmp/.ansible/tmp"

  pre_tasks:
    - name: Ensure Ansible remote tmp directory exists and is writable
      file:
        path: "{{ ansible_remote_tmp }}"
        state: directory
        mode: "1777"
        owner: root
        group: root

    - name: Detect if custom DB vars are provided
      set_fact:
        db_vars_provided: "{{ (db_password | length > 0) and (db_user | length > 0) and (db_name | length > 0) }}"

    # DNS (note: overwriting resolv.conf may be temporary depending on OS)
    - name: Configure resolv.conf with Google DNS (Ubuntu)
      when: ansible_distribution == "Ubuntu"
      shell: "echo nameserver 8.8.8.8 > /etc/resolv.conf"
      args:
        warn: false

    - name: Configure resolv.conf with Google DNS (RHEL)
      when: ansible_os_family == "RedHat"
      shell: "echo nameserver 8.8.8.8 > /etc/resolv.conf"
      args:
        warn: false

    # Clear proxy settings (fixes your invalid /etc/yum.conf.d path)
    - name: Clear apt proxy settings (Ubuntu)
      when: ansible_distribution == "Ubuntu"
      shell: "truncate -s 0 /etc/apt/apt.conf.d/90curtin-aptproxy"
      args:
        warn: false
      failed_when: false

    - name: Remove proxy lines from /etc/yum.conf (RHEL)
      when: ansible_os_family == "RedHat"
      lineinfile:
        path: /etc/yum.conf
        regexp: '^(proxy|proxy_username|proxy_password)='
        state: absent
      failed_when: false

  tasks:
    # -----------------------------
    # Ubuntu install
    # -----------------------------
    - name: Install required packages (Ubuntu)
      when: ansible_distribution == "Ubuntu"
      apt:
        name:
          - software-properties-common
          - python3-pymysql
          - curl
          - gnupg2
          - apt-transport-https
        state: present
        update_cache: yes

    - name: Create keyrings directory (Ubuntu)
      when: ansible_distribution == "Ubuntu"
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: "0755"

    - name: Download MariaDB GPG key (Ubuntu)
      when: ansible_distribution == "Ubuntu"
      get_url:
        url: https://mariadb.org/mariadb_release_signing_key.pgp
        dest: /etc/apt/keyrings/mariadb-keyring.pgp
        mode: "0644"

    - name: Add MariaDB Repository (Ubuntu)
      when: ansible_distribution == "Ubuntu"
      copy:
        content: |
          # MariaDB 11.2 repository
          Types: deb
          URIs: https://mirror.marwan.ma/mariadb/repo/11.2/ubuntu
          Suites: jammy
          Components: main main/debug
          Signed-By: /etc/apt/keyrings/mariadb-keyring.pgp
        dest: /etc/apt/sources.list.d/mariadb.sources
        mode: "0644"

    - name: Update apt cache (Ubuntu)
      when: ansible_distribution == "Ubuntu"
      apt:
        update_cache: yes

    - name: Install MariaDB (Ubuntu)
      when: ansible_distribution == "Ubuntu"
      apt:
        name:
          - mariadb-server
          - mariadb-client
        state: present

    # -----------------------------
    # RHEL install
    # -----------------------------
    - name: Register and subscribe RHEL system
      when: ansible_os_family == "RedHat"
      command: subscription-manager register --username {{ rhel_username }} --password {{ rhel_password }} --auto-attach
      register: subscription_result
      failed_when: subscription_result.rc != 0 and 'This system is already registered' not in subscription_result.stderr
      changed_when: subscription_result.rc == 0

    - name: Enable required RHEL repositories
      when: ansible_os_family == "RedHat"
      command: subscription-manager repos --enable rhel-{{ ansible_distribution_major_version }}-for-x86_64-appstream-rpms
      register: repo_result
      failed_when: repo_result.rc != 0 and 'already enabled' not in repo_result.stderr
      changed_when: repo_result.rc == 0

    - name: Download MariaDB repo setup script (RHEL)
      when: ansible_os_family == "RedHat"
      get_url:
        url: https://downloads.mariadb.com/MariaDB/mariadb_repo_setup
        dest: /tmp/mariadb_repo_setup
        mode: "0755"

    - name: Execute MariaDB repo setup script (RHEL)
      when: ansible_os_family == "RedHat"
      command: /tmp/mariadb_repo_setup
      args:
        creates: /etc/yum.repos.d/mariadb.repo

    - name: Install MariaDB dependencies (RHEL)
      when: ansible_os_family == "RedHat"
      yum:
        name:
          - perl-DBI
          - libaio
          - libsepol
          - lsof
          - boost-program-options
          - python3-PyMySQL
        state: present

    - name: Install MariaDB server (RHEL)
      when: ansible_os_family == "RedHat"
      yum:
        name: mariadb-server
        state: present

    # -----------------------------
    # Common config
    # -----------------------------
    - name: Enable and start MariaDB service
      systemd:
        name: mariadb
        enabled: yes
        state: started

    - name: Wait until MariaDB responds (mysqladmin ping)
      command: mysqladmin ping
      register: mariadb_ping
      retries: 15
      delay: 2
      until: mariadb_ping.rc == 0
      changed_when: false

    # Make sure mysql Python modules are usable on both OS families
    - name: Ensure community.mysql collection is available (informational)
      debug:
        msg: "If mysql_* modules fail, install community.mysql on the Ansible runner."
      changed_when: false

    # Set root password using module (idempotent-ish)
    - name: Set root password (best effort)
      community.mysql.mysql_user:
        name: root
        host: localhost
        password: "{{ mysql_root_password }}"
        login_user: root
        login_password: ""
        check_implicit_admin: true
        priv: "*.*:ALL,GRANT"
        state: present
      register: root_pw_result
      failed_when: false

    - name: Remove anonymous users
      community.mysql.mysql_user:
        name: ""
        host_all: true
        login_user: root
        login_password: "{{ mysql_root_password }}"
        state: absent

    - name: Remove test database
      community.mysql.mysql_db:
        name: test
        login_user: root
        login_password: "{{ mysql_root_password }}"
        state: absent

    - name: Create database if variables are provided
      when: db_vars_provided
      community.mysql.mysql_db:
        name: "{{ db_name }}"
        login_user: root
        login_password: "{{ mysql_root_password }}"
        state: present

    - name: Create user and grant privileges if variables are provided
      when: db_vars_provided
      community.mysql.mysql_user:
        name: "{{ db_user }}"
        host: "%"
        password: "{{ db_password }}"
        priv: "{{ db_name }}.*:ALL"
        login_user: root
        login_password: "{{ mysql_root_password }}"
        state: present

    # Final validation (this should be what Morpheus uses as "real success")
    - name: Validation - show MariaDB version
      command: mysql --user=root --password={{ mysql_root_password }} -e "SELECT VERSION();"
      register: mariadb_version
      changed_when: false

    - name: Print status of MariaDB setup
      debug:
        msg: "MariaDB OK. Version={{ mariadb_version.stdout_lines | default([]) }} DB vars provided={{ db_vars_provided }} User={{ db_user }} DB={{ db_name }}"
