---
- name: Install and Configure MariaDB (Ubuntu)
  hosts: all
  become: true
  gather_facts: true

  vars:
    mariadb_admin_password: "{{ hostvars[inventory_hostname]['morpheus']['customOptions']['dbCustomPassword'] | default('rootroot') }}"
    db_password: "{{ hostvars[inventory_hostname]['morpheus']['customOptions']['dbCustomPassword'] | default('') }}"
    db_user: "{{ hostvars[inventory_hostname]['morpheus']['customOptions']['dbCustomUser'] | default('') }}"
    db_name: "{{ hostvars[inventory_hostname]['morpheus']['customOptions']['dbCustomName'] | default('') }}"
    ansible_remote_tmp: "/var/tmp/.ansible/tmp"

  tasks:
    - name: Fail if not Ubuntu (this playbook is Ubuntu-focused)
      when: ansible_distribution != "Ubuntu"
      fail:
        msg: "This MariaDB playbook supports Ubuntu only. Detected: {{ ansible_distribution }}"

    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install MariaDB server + client
      apt:
        name:
          - mariadb-server
          - mariadb-client
        state: present

    - name: Ensure MariaDB is started and enabled
      systemd:
        name: mariadb
        state: started
        enabled: yes

    - name: Wait for MariaDB socket
      wait_for:
        path: /run/mysqld/mysqld.sock
        timeout: 60

    # Root should be socket-based so sudo mariadb always works
    - name: Force root to unix_socket authentication (MariaDB-safe)
      command: >
        sudo mariadb -NBe
        "ALTER USER 'root'@'localhost' IDENTIFIED VIA unix_socket;
         FLUSH PRIVILEGES;"
      changed_when: true

    - name: Verify root socket login works
      command: sudo mariadb -NBe "SELECT 1;"
      changed_when: false

    # Admin user for password-based automation/tests (force-reset password every run)
    - name: Ensure admin user exists + force-reset password (MariaDB portable)
      command: >
        sudo mariadb -NBe
        "CREATE USER IF NOT EXISTS 'admin'@'localhost' IDENTIFIED BY '{{ mariadb_admin_password }}';
         SET PASSWORD FOR 'admin'@'localhost' = PASSWORD('{{ mariadb_admin_password }}');
         GRANT ALL PRIVILEGES ON *.* TO 'admin'@'localhost' WITH GRANT OPTION;
         FLUSH PRIVILEGES;"
      changed_when: true

    - name: Create database if provided
      when: db_name | length > 0
      command: >
        sudo mariadb -NBe
        "CREATE DATABASE IF NOT EXISTS \`{{ db_name }}\`;"

    - name: Create app user and grant privileges if provided (force-reset password)
      when: (db_user | length > 0) and (db_password | length > 0) and (db_name | length > 0)
      command: >
        sudo mariadb -NBe
        "CREATE USER IF NOT EXISTS '{{ db_user }}'@'localhost' IDENTIFIED BY '{{ db_password }}';
         SET PASSWORD FOR '{{ db_user }}'@'localhost' = PASSWORD('{{ db_password }}');
         GRANT ALL PRIVILEGES ON \`{{ db_name }}\`.* TO '{{ db_user }}'@'localhost';
         FLUSH PRIVILEGES;"
      changed_when: true

    - name: Show MariaDB version
      command: mariadb --version
      register: mariadb_version
      changed_when: false

    - name: Print MariaDB version
      debug:
        var: mariadb_version.stdout

    - name: Print login hints
      debug:
        msg:
          - "Root login (socket): sudo mariadb"
          - "Admin login (password): mariadb -u admin -p  (password is dbCustomPassword or 'rootroot')"
