---
- name: Install MinIO on Ubuntu 24.04
  hosts: all
  become: true
  vars:
    minio_home: /opt/minio
    minio_user: minio
    minio_version: "20241029160148.0.0"
    minio_console_port: 9001
    minio_root_user: admin
    minio_root_password: Password123!

  tasks:

    # DNS & proxy setup
    - name: Configure /etc/resolv.conf with Google DNS
      copy:
        dest: /etc/resolv.conf
        content: |
          nameserver 8.8.8.8
        owner: root
        group: root
        mode: '0644'

    - name: Clear apt proxy settings
      copy:
        dest: /etc/apt/apt.conf.d/90curtin-aptproxy
        content: ""
        owner: root
        group: root
        mode: '0644'

    # System prep
    - name: Update and upgrade APT packages
      apt:
        update_cache: yes
        upgrade: dist
        autoremove: yes

    - name: Install dependencies
      apt:
        name:
          - wget
          - curl
          - sudo
          - tar
        state: present

    # User & directories
    - name: Create MinIO system user
      user:
        name: "{{ minio_user }}"
        shell: /bin/bash
        create_home: yes

    - name: Create MinIO directories
      file:
        path: "{{ item }}"
        state: directory
        owner: "{{ minio_user }}"
        group: "{{ minio_user }}"
        mode: '0755'
      loop:
        - "{{ minio_home }}"
        - "{{ minio_home }}/data"

    # Download & install MinIO
    - name: Download MinIO package
      get_url:
        url: "https://dl.min.io/server/minio/release/linux-amd64/archive/minio_{{ minio_version }}_amd64.deb"
        dest: "/tmp/minio.deb"

    - name: Install MinIO package
      apt:
        deb: /tmp/minio.deb
        state: present

    # Systemd service
    - name: Create MinIO systemd service
      copy:
        dest: /etc/systemd/system/minio.service
        content: |
          [Unit]
          Description=MinIO
          Documentation=https://min.io/docs
          Wants=network-online.target
          After=network-online.target
          AssertFileIsExecutable=/usr/local/bin/minio

          [Service]
          User={{ minio_user }}
          Group={{ minio_user }}
          WorkingDirectory={{ minio_home }}
          Environment="MINIO_ROOT_USER={{ minio_root_user }}"
          Environment="MINIO_ROOT_PASSWORD={{ minio_root_password }}"
          ExecStart=/usr/local/bin/minio server {{ minio_home }}/data --console-address :{{ minio_console_port }}
          Restart=always
          LimitNOFILE=65536
          TimeoutStopSec=infinity
          SendSIGKILL=no

          [Install]
          WantedBy=multi-user.target

    - name: Reload systemd
      systemd:
        daemon_reload: yes

    - name: Enable and start MinIO service
      systemd:
        name: minio
        state: started
        enabled: yes

    - name: Clean up downloaded MinIO file
      file:
        path: /tmp/minio.deb
        state: absent

    - name: Wait for MinIO to start
      wait_for:
        port: "{{ minio_console_port }}"
        delay: 5
        timeout: 300

    - name: Show completion message
      debug:
        msg:
          - "MinIO installed successfully."
          - "Access the MinIO console at http://<server-ip>:{{ minio_console_port }}"
          - "Default credentials:"
          - "Username: {{ minio_root_user }}"
          - "Password: {{ minio_root_password }}"
          - "Change these credentials after first login!"


