---
- name: Install Apache NiFi on Ubuntu 24.04
  hosts: all
  become: yes
  
  vars:
    nifi_version: "1.24.0"
    nifi_user: nifi
    nifi_group: nifi
    nifi_home: /opt/nifi  # Simple path, no symlink
    nifi_port: 8080

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install Java and tools
      apt:
        name:
          - openjdk-17-jdk
          - unzip
          - wget
        state: present

    - name: Create NiFi group
      group:
        name: "{{ nifi_group }}"
        system: yes

    - name: Create NiFi user
      user:
        name: "{{ nifi_user }}"
        group: "{{ nifi_group }}"
        system: yes
        shell: /usr/sbin/nologin
        create_home: no

    - name: Download NiFi
      shell: |
        wget -q --no-check-certificate \
          "https://archive.apache.org/dist/nifi/{{ nifi_version }}/nifi-{{ nifi_version }}-bin.zip" \
          -O "/tmp/nifi-{{ nifi_version }}.zip"
      args:
        creates: "/tmp/nifi-{{ nifi_version }}.zip"

    - name: Extract and setup NiFi (all in one)
      shell: |
        # Extract
        unzip -q "/tmp/nifi-{{ nifi_version }}.zip" -d /opt
        # Rename to simple path
        mv "/opt/nifi-{{ nifi_version }}" "{{ nifi_home }}"
        # Set permissions
        chown -R {{ nifi_user }}:{{ nifi_group }} "{{ nifi_home }}"
      args:
        creates: "{{ nifi_home }}"  # Only run if NiFi not installed

    - name: Configure NiFi to listen on all interfaces
      lineinfile:
        path: "{{ nifi_home }}/conf/nifi.properties"
        regexp: "^nifi.web.http.host="
        line: "nifi.web.http.host=0.0.0.0"
        create: yes
        backup: yes

    - name: Configure NiFi port
      lineinfile:
        path: "{{ nifi_home }}/conf/nifi.properties"
        regexp: "^nifi.web.http.port="
        line: "nifi.web.http.port={{ nifi_port }}"
        create: yes
        backup: yes

    - name: Check if NiFi is already running
      shell: |
        pgrep -f nifi 2>/dev/null || echo "NOT_RUNNING"
      register: nifi_status
      changed_when: false
      ignore_errors: yes

    - name: Start NiFi
      command: "{{ nifi_home }}/bin/nifi.sh start"
      become_user: "{{ nifi_user }}"
      when: "'NOT_RUNNING' in nifi_status.stdout"
      args:
        creates: "{{ nifi_home }}/logs/nifi-bootstrap.log"

    - name: Wait for NiFi to start
      wait_for:
        port: "{{ nifi_port }}"
        delay: 15
        timeout: 180
        state: started

    - name: Clean up download
      file:
        path: "/tmp/nifi-{{ nifi_version }}.zip"
        state: absent
      ignore_errors: yes

    - name: Show installation info
      debug:
        msg: |
          NiFi {{ nifi_version }} installed successfully!
          
          Access: http://{{ ansible_default_ipv4.address }}:{{ nifi_port }}/nifi
          
          Installation: {{ nifi_home }}
          Run as user: {{ nifi_user }}
          
