---
- name: Install OpenStack DevStack on Ubuntu 24.04
  hosts: all
  become: true

  vars:
    devstack_user: stack
    devstack_repo: https://opendev.org/openstack/devstack.git
    devstack_dir: /opt/devstack
    local_conf_content: |
      [[local|localrc]]
      ADMIN_PASSWORD=admin
      DATABASE_PASSWORD=admin
      RABBIT_PASSWORD=admin
      SERVICE_PASSWORD=admin
      HOST_IP={{ ansible_default_ipv4.address }}

  tasks:
    # 1. Basic system setup
    - name: Configure resolv.conf with Google DNS
      copy:
        dest: /etc/resolv.conf
        content: "nameserver 8.8.8.8\n"

    - name: Clear apt proxy settings
      copy:
        dest: /etc/apt/apt.conf.d/90curtin-aptproxy
        content: ""

    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install base dependencies
      apt:
        name:
          - git
          - sudo
          - net-tools
          - python3
          - python3-pip
          - python3-dev
          - build-essential
        state: present

    # 2. Create stack user
    - name: Create 'stack' user
      user:
        name: "{{ devstack_user }}"
        shell: /bin/bash
        groups: sudo
        append: yes
        create_home: yes

    - name: Allow 'stack' user passwordless sudo
      copy:
        dest: /etc/sudoers.d/99_stack_nopasswd
        content: "{{ devstack_user }} ALL=(ALL) NOPASSWD: ALL"
        mode: '0440'

    # 3. Clone DevStack
    - name: Clone DevStack repository
      become_user: "{{ devstack_user }}"
      git:
        repo: "{{ devstack_repo }}"
        dest: "{{ devstack_dir }}"
        version: master

    - name: Create local.conf with custom configuration
      become_user: "{{ devstack_user }}"
      copy:
        dest: "{{ devstack_dir }}/local.conf"
        content: "{{ local_conf_content }}"
        mode: '0644'

    # 4. Run DevStack
    - name: Run stack.sh with FORCE=yes
      become_user: "{{ devstack_user }}"
      shell: |
        cd {{ devstack_dir }}
        FORCE=yes ./stack.sh
      args:
        executable: /bin/bash

