- name: Install & Secure Redis 6+ on Ubuntu 24.04
  hosts: all
  become: true
  gather_facts: true

  vars:
    redis_port: 6379
    redis_bind: "127.0.0.1"  # Redis is accessible ONLY from the same machine. Change to private IP (better option )  & ordo :  0.0.0.0 .
    redis_password: "redis"
    redis_maxmemory: "512mb"
    redis_policy: "allkeys-lru"

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install Redis
      apt:
        name: redis-server
        state: present

    - name: Stop Redis before configuration
      systemd:
        name: redis-server
        state: stopped

    - name: Ensure Redis config file exists
      file:
        path: /etc/redis/redis.conf
        state: touch
        owner: redis
        group: redis
        mode: '0640'

    - name: Configure Redis securely (ACL-only)
      blockinfile:
        path: /etc/redis/redis.conf
        create: yes
        marker: "# {mark} REDIS MANAGED BLOCK"
        block: |
          bind {{ redis_bind }}
          port {{ redis_port }}
          protected-mode yes
          supervised systemd

          # Redis 6+ ACL for default user
          user default on >{{ redis_password }} ~* +@all

          maxmemory {{ redis_maxmemory }}
          maxmemory-policy {{ redis_policy }}

          appendonly yes
        backup: yes

    - name: Set Redis config permissions
      file:
        path: /etc/redis/redis.conf
        owner: redis
        group: redis
        mode: '0640'

    - name: Reload systemd daemon
      systemd:
        daemon_reload: yes

    - name: Start Redis
      systemd:
        name: redis-server
        enabled: yes
        state: started

    - name: Wait for Redis to be available
      wait_for:
        port: "{{ redis_port }}"
        timeout: 60

    - name: Verify Redis authentication
      command: redis-cli -a "{{ redis_password }}" ping
      register: redis_ping
      changed_when: false

    - name: Display Redis status
      debug:
        msg: "✅ Redis is running and secured: {{ redis_ping.stdout }}"


