---
- name: Install WordPress on Ubuntu
  hosts: all
  become: yes

  vars:
    mysql_database: wordpress_db
    mysql_user: wordpress_user
    mysql_password: wordpress
    http_host: localhost
    http_conf: wordpress.conf

  tasks:
    - name: Install required packages
      apt:
        name:
          - apache2
          - mysql-server
          - php8.3
          - php8.3-mysql
          - php8.3-curl
          - php8.3-gd
          - php8.3-mbstring
          - php8.3-xml
          - php8.3-soap
          - php8.3-intl
          - php8.3-zip
          - unzip
          - python3-pymysql
        state: present
        update_cache: yes

    - name: Start and enable services
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop:
        - apache2
        - mysql

    - name: Create WordPress database
      community.mysql.mysql_db:
        name: "{{ mysql_database }}"
        state: present
        login_unix_socket: /var/run/mysqld/mysqld.sock

    - name: Create WordPress MySQL user
      community.mysql.mysql_user:
        name: "{{ mysql_user }}"
        password: "{{ mysql_password }}"
        priv: "{{ mysql_database }}.*:ALL"
        host: localhost
        state: present
        login_unix_socket: /var/run/mysqld/mysqld.sock

    - name: Download WordPress
      shell: curl -fsSL https://wordpress.org/latest.tar.gz -o /tmp/wordpress.tar.gz

    - name: Extract WordPress
      unarchive:
        src: /tmp/wordpress.tar.gz
        dest: /var/www/html/
        remote_src: yes

    - name: Set permissions
      file:
        path: /var/www/html/wordpress
        owner: www-data
        group: www-data
        mode: '0755'
        recurse: yes

    - name: Create wp-config.php
      copy:
        src: /var/www/html/wordpress/wp-config-sample.php
        dest: /var/www/html/wordpress/wp-config.php
        remote_src: yes

    - name: Configure wp-config.php
      replace:
        path: /var/www/html/wordpress/wp-config.php
        regexp: "{{ item.regexp }}"
        replace: "{{ item.replace }}"
      loop:
        - { regexp: 'database_name_here', replace: "{{ mysql_database }}" }
        - { regexp: 'username_here', replace: "{{ mysql_user }}" }
        - { regexp: 'password_here', replace: "{{ mysql_password }}" }

    - name: Enable Apache rewrite
      command: a2enmod rewrite

    - name: Create Apache VirtualHost
      copy:
        dest: "/etc/apache2/sites-available/{{ http_conf }}"
        content: |
          <VirtualHost *:80>
            ServerName {{ http_host }}
            DocumentRoot /var/www/html/wordpress
            <Directory /var/www/html/wordpress>
              AllowOverride All
              Require all granted
            </Directory>
          </VirtualHost>

    - name: Enable site
      command: a2ensite {{ http_conf }}

    - name: Disable default site
      command: a2dissite 000-default.conf

    - name: Reload Apache
      service:
        name: apache2
        state: reloaded
