---
- name: Provision WordPress on Ubuntu (Single File - FIXED list install)
  hosts: all
  become: true
  gather_facts: true

  vars:
    wp_db_name: wordpress
    wp_db_user: wpuser
    wp_db_password: wp_pass_123
    wp_db_root_password: root_pass_123
    wp_install_dir: /var/www/wordpress

    base_packages:
      - nginx
      - mariadb-server
      - unzip
      - curl

    php_packages:
      - php-fpm
      - php-mysql
      - php-curl
      - php-gd
      - php-mbstring
      - php-xml
      - php-zip

  tasks:

    - name: Ensure Ubuntu OS
      assert:
        that:
          - ansible_distribution == "Ubuntu"
        fail_msg: "This playbook supports Ubuntu only"

    - name: Update apt cache
      apt:
        update_cache: true
        cache_valid_time: 3600

    - name: Install base packages (NO nested lists)
      apt:
        name: "{{ base_packages }}"
        state: present

    - name: Install PHP packages (NO nested lists)
      apt:
        name: "{{ php_packages }}"
        state: present

    - name: Ensure MariaDB is started
      service:
        name: mariadb
        state: started
        enabled: true

    - name: Secure MariaDB root user (idempotent marker)
      shell: |
        mysql -u root <<EOF
        ALTER USER 'root'@'localhost' IDENTIFIED BY '{{ wp_db_root_password }}';
        DELETE FROM mysql.user WHERE User='';
        DROP DATABASE IF EXISTS test;
        FLUSH PRIVILEGES;
        EOF
        touch /root/.mariadb-secured
      args:
        creates: /root/.mariadb-secured

    - name: Create WordPress database and user
      shell: |
        mysql -u root -p{{ wp_db_root_password }} <<EOF
        CREATE DATABASE IF NOT EXISTS {{ wp_db_name }};
        CREATE USER IF NOT EXISTS '{{ wp_db_user }}'@'localhost' IDENTIFIED BY '{{ wp_db_password }}';
        GRANT ALL PRIVILEGES ON {{ wp_db_name }}.* TO '{{ wp_db_user }}'@'localhost';
        FLUSH PRIVILEGES;
        EOF

    - name: Download WordPress
      get_url:
        url: https://wordpress.org/latest.tar.gz
        dest: /tmp/wordpress.tar.gz
        mode: '0644'

    - name: Extract WordPress
      unarchive:
        src: /tmp/wordpress.tar.gz
        dest: /var/www/
        remote_src: true

    - name: Set ownership
      file:
        path: "{{ wp_install_dir }}"
        owner: www-data
        group: www-data
        recurse: true

    - name: Configure wp-config.php
      copy:
        dest: "{{ wp_install_dir }}/wp-config.php"
        owner: www-data
        group: www-data
        mode: '0644'
        content: |
          <?php
          define('DB_NAME', '{{ wp_db_name }}');
          define('DB_USER', '{{ wp_db_user }}');
          define('DB_PASSWORD', '{{ wp_db_password }}');
          define('DB_HOST', 'localhost');
          define('DB_CHARSET', 'utf8');
          define('DB_COLLATE', '');
          $table_prefix = 'wp_';
          define('WP_DEBUG', false);
          if ( !defined('ABSPATH') )
            define('ABSPATH', dirname(__FILE__) . '/');
          require_once(ABSPATH . 'wp-settings.php');

    - name: Ensure Nginx is started
      service:
        name: nginx
        state: started
        enabled: true
