---
- name: Provision WordPress on Ubuntu (Morpheus Safe, Auto PHP)
  hosts: all
  become: true

  vars:
    wp_domain: "example.com"
    wp_root: "/var/www/wordpress"

    db_name: "wordpress"
    db_user: "wpuser"
    db_password: "StrongPassword123!"
    db_root_password: "RootDBPassword123!"

  pre_tasks:
    - name: Ensure Ubuntu
      assert:
        that:
          - ansible_distribution == "Ubuntu"
        fail_msg: "This playbook supports Ubuntu only."

    - name: Set PHP version based on Ubuntu release
      set_fact:
        php_version: >-
          {% if ansible_distribution_version is version('24.04', '>=') %}
          8.3
          {% elif ansible_distribution_version is version('22.04', '>=') %}
          8.1
          {% else %}
          7.4
          {% endif %}

    - name: Update apt cache
      apt:
        update_cache: true
        cache_valid_time: 3600

  tasks:
    - name: Install required packages
      apt:
        name:
          - nginx
          - mariadb-server
          - php{{ php_version }}-fpm
          - php{{ php_version }}-mysql
          - php{{ php_version }}-curl
          - php{{ php_version }}-gd
          - php{{ php_version }}-mbstring
          - php{{ php_version }}-xml
          - php{{ php_version }}-zip
          - unzip
          - curl
        state: present

    - name: Ensure services are running
      service:
        name: "{{ item }}"
        state: started
        enabled: true
      loop:
        - nginx
        - mariadb
        - php{{ php_version }}-fpm

    - name: Set MariaDB root password
      shell: |
        mysql -u root <<EOF
        ALTER USER 'root'@'localhost' IDENTIFIED BY '{{ db_root_password }}';
        FLUSH PRIVILEGES;
        EOF
      args:
        executable: /bin/bash
      ignore_errors: true

    - name: Create WordPress database and user
      shell: |
        mysql -u root -p'{{ db_root_password }}' <<EOF
        CREATE DATABASE IF NOT EXISTS {{ db_name }};
        CREATE USER IF NOT EXISTS '{{ db_user }}'@'%' IDENTIFIED BY '{{ db_password }}';
        GRANT ALL PRIVILEGES ON {{ db_name }}.* TO '{{ db_user }}'@'%';
        FLUSH PRIVILEGES;
        EOF
      args:
        executable: /bin/bash

    - name: Create web root
      file:
        path: "{{ wp_root }}"
        state: directory
        owner: www-data
        group: www-data
        mode: "0755"

    - name: Download and extract WordPress
      shell: |
        curl -s https://wordpress.org/latest.tar.gz | tar -xz -C /tmp
      args:
        creates: /tmp/wordpress

    - name: Deploy WordPress files
      copy:
        src: /tmp/wordpress/
        dest: "{{ wp_root }}"
        owner: www-data
        group: www-data
        mode: "0755"
        remote_src: true

    - name: Create wp-config.php
      copy:
        dest: "{{ wp_root }}/wp-config.php"
        owner: www-data
        group: www-data
        mode: "0640"
        content: |
          <?php
          define('DB_NAME', '{{ db_name }}');
          define('DB_USER', '{{ db_user }}');
          define('DB_PASSWORD', '{{ db_password }}');
          define('DB_HOST', 'localhost');

          define('DB_CHARSET', 'utf8');
          define('DB_COLLATE', '');

          define('WP_DEBUG', false);

          $table_prefix = 'wp_';

          if ( ! defined('ABSPATH') ) {
              define('ABSPATH', __DIR__ . '/');
          }

          require_once ABSPATH . 'wp-settings.php';
          ?>

    - name: Configure NGINX site
      copy:
        dest: /etc/nginx/sites-available/wordpress
        content: |
          server {
              listen 80;
              server_name {{ wp_domain }};

              root {{ wp_root }};
              index index.php index.html;

              location / {
                  try_files $uri $uri/ /index.php?$args;
              }

              location ~ \.php$ {
                  include snippets/fastcgi-php.conf;
                  fastcgi_pass unix:/run/php/php{{ php_version }}-fpm.sock;
              }

              location ~* \.(js|css|png|jpg|jpeg|gif|ico)$ {
                  expires max;
                  log_not_found off;
              }
          }
      notify: Reload NGINX

    - name: Enable NGINX site
      file:
        src: /etc/nginx/sites-available/wordpress
        dest: /etc/nginx/sites-enabled/wordpress
        state: link
        force: true

    - name: Remove default NGINX site
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent

  handlers:
    - name: Reload NGINX
      service:
        name: nginx
        state: reloaded
