---
- name: Install WordPress using bertvv roles (RHEL/CentOS 7)
  hosts: all
  become: true
  gather_facts: true

  vars:
    # Install roles into ./roles next to this playbook (Ansible finds ./roles by default)
    roles_dir: "{{ playbook_dir }}/roles"

    # --- Hardcoded DB creds (per your earlier request) ---
    wp_db_name: "wordpress"
    wp_db_user: "wpuser"
    wp_db_password: "ChangeMeOnceAndKeepSameEverywhere"
    mariadb_root_password: "ChangeMeRootPassword"

  pre_tasks:
    - name: Ensure roles directory exists on controller
      ansible.builtin.file:
        path: "{{ roles_dir }}"
        state: directory
        mode: "0755"
      delegate_to: localhost
      run_once: true

    - name: Check if required roles are already installed (on controller)
      ansible.builtin.stat:
        path: "{{ roles_dir }}/{{ item }}"
      loop:
        - "bertvv.httpd"
        - "bertvv.mariadb"
        - "bertvv.wordpress"
      register: role_stats
      delegate_to: localhost
      run_once: true

    - name: Install missing roles from Ansible Galaxy (on controller)
      ansible.builtin.command: >
        ansible-galaxy role install -p "{{ roles_dir }}" {{ item.item }}
      args:
        creates: "{{ roles_dir }}/{{ item.item }}"
      loop: "{{ role_stats.results }}"
      when: not item.stat.exists
      delegate_to: localhost
      run_once: true

  roles:
    # 1) MariaDB server + create DB/user for WordPress
    - role: bertvv.mariadb
      vars:
        mariadb_root_password: "{{ mariadb_root_password }}"
        mariadb_databases:
          - name: "{{ wp_db_name }}"
            collation: "utf8mb4_unicode_ci"
            encoding: "utf8mb4"
        mariadb_users:
          - name: "{{ wp_db_user }}"
            password: "{{ wp_db_password }}"
            host: "localhost"
            priv: "{{ wp_db_name }}.*:ALL"

    # 2) WordPress (installs deps, downloads WP tarball, configures Apache + wp-config.php)
    - role: bertvv.wordpress
      vars:
        wordpress_database_host: "localhost"
        wordpress_database: "{{ wp_db_name }}"
        wordpress_user: "{{ wp_db_user }}"
        wordpress_password: "{{ wp_db_password }}"
        # Optional knobs supported by the role:
        wordpress_allow_file_mods: true
        wordpress_automatic_updates: false
        wordpress_debug: false
        wordpress_force_ssl: false
        # wordpress_version: "6.0.2"   # role default; set if you want a specific version
