---
- name: Provision WordPress on Ubuntu 24.04 (Nginx + PHP-FPM + MariaDB) - single file
  hosts: all
  become: true

  vars:
    # ---- WordPress + DB settings (hardcoded, same for every provisioning) ----
    wp_site_name: "wordpress"
    wp_root: /var/www/wordpress

    wp_db_name: wordpress
    wp_db_user: wpuser
    wp_db_password: "WP_DB_PASSWORD_SAME_EVERY_TIME_CHANGE_ME"

    # Ubuntu 24.04 default PHP version is typically 8.3
    php_fpm_sock: /run/php/php8.3-fpm.sock

    # WordPress download
    wp_tmp_dir: /tmp/wordpress-install
    wp_tgz: /tmp/wordpress.tar.gz
    wp_url: https://wordpress.org/latest.tar.gz

    # Fixed salts/keys (kept static to stay single-file + deterministic)
    wp_auth_keys: |
      define('AUTH_KEY',         'put-some-long-random-string-here-1');
      define('SECURE_AUTH_KEY',  'put-some-long-random-string-here-2');
      define('LOGGED_IN_KEY',    'put-some-long-random-string-here-3');
      define('NONCE_KEY',        'put-some-long-random-string-here-4');
      define('AUTH_SALT',        'put-some-long-random-string-here-5');
      define('SECURE_AUTH_SALT', 'put-some-long-random-string-here-6');
      define('LOGGED_IN_SALT',   'put-some-long-random-string-here-7');
      define('NONCE_SALT',       'put-some-long-random-string-here-8');

  handlers:
    - name: reload nginx
      ansible.builtin.service:
        name: nginx
        state: reloaded

  tasks:
    - name: Ensure Ubuntu 24.04
      ansible.builtin.assert:
        that:
          - ansible_distribution == "Ubuntu"
          - ansible_distribution_version is version('24.04', '>=')
        fail_msg: "This playbook is intended for Ubuntu 24.04+."

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600

    - name: Install base packages
      ansible.builtin.apt:
        name:
          - nginx
          - mariadb-server
          - unzip
          - curl
          - tar
        state: present

    - name: Install PHP packages
      ansible.builtin.apt:
        name:
          - php-fpm
          - php-mysql
          - php-curl
          - php-gd
          - php-mbstring
          - php-xml
          - php-zip
        state: present

    - name: Ensure services are started and enabled
      ansible.builtin.service:
        name: "{{ item }}"
        state: started
        enabled: true
      loop:
        - mariadb
        - nginx

    # ----------------------- MariaDB DB + User (via mysql CLI) -----------------------
    - name: Ensure MariaDB socket exists (wait up to 30s)
      ansible.bui
