---
- name: Provision WordPress on Ubuntu (Morpheus Single File, Safe)
  hosts: all
  become: true
  gather_facts: true

  vars:
    wp_install_dir: /var/www/wordpress
    wp_db_name: wordpress
    wp_db_user: wpuser
    wp_db_password: wp_password_123
    wp_db_host: localhost

  tasks:

    - name: Ensure Ubuntu OS
      assert:
        that:
          - ansible_distribution == "Ubuntu"
        fail_msg: "This playbook supports Ubuntu only"

    - name: Set PHP packages based on Ubuntu version
      set_fact:
        php_packages: >-
          {{
            [
              'php-fpm',
              'php-mysql',
              'php-curl',
              'php-gd',
              'php-mbstring',
              'php-xml',
              'php-zip'
            ]
          }}

    - name: Update apt cache
      apt:
        update_cache: true
        cache_valid_time: 3600

    - name: Install required packages
      apt:
        name:
          - nginx
          - mariadb-server
          - unzip
          - curl
          - "{{ php_packages }}"
        state: present

    - name: Ensure MariaDB is running
      service:
        name: mariadb
        state: started
        enabled: true

    - name: Create WordPress database
      shell: |
        mysql -e "CREATE DATABASE IF NOT EXISTS {{ wp_db_name }};
        CREATE USER IF NOT EXISTS '{{ wp_db_user }}'@'localhost' IDENTIFIED BY '{{ wp_db_password }}';
        GRANT ALL PRIVILEGES ON {{ wp_db_name }}.* TO '{{ wp_db_user }}'@'localhost';
        FLUSH PRIVILEGES;"
      args:
        creates: "/var/lib/mysql/{{ wp_db_name }}"

    - name: Create WordPress install directory
      file:
        path: "{{ wp_install_dir }}"
        state: directory
        owner: www-data
        group: www-data
        mode: "0755"

    - name: Download and extract WordPress (curl, Morpheus-safe)
      shell: |
        rm -rf /tmp/wordpress
        curl -fsSL https://wordpress.org/latest.tar.gz | tar -xz -C /tmp
      args:
        creates: /tmp/wordpress

    - name: Deploy WordPress files
      copy:
        src: /tmp/wordpress/
        dest: "{{ wp_install_dir }}"
        owner: www-data
        group: www-data
        mode: "0755"
        remote_src: true

    - name: Create wp-config.php
      copy:
        dest: "{{ wp_install_dir }}/wp-config.php"
        owner: www-data
        group: www-data
        mode: "0644"
        content: |
          <?php
          define('DB_NAME', '{{ wp_db_name }}');
          define('DB_USER', '{{ wp_db_user }}');
          define('DB_PASSWORD', '{{ wp_db_password }}');
          define('DB_HOST', '{{ wp_db_host }}');
          define('DB_CHARSET', 'utf8');
          define('DB_COLLATE', '');

          define('AUTH_KEY',         'change-me');
          define('SECURE_AUTH_KEY',  'change-me');
          define('LOGGED_IN_KEY',    'change-me');
          define('NONCE_KEY',        'change-me');
          define('AUTH_SALT',        'change-me');
          define('SECURE_AUTH_SALT', 'change-me');
          define('LOGGED_IN_SALT',   'change-me');
          define('NONCE_SALT',       'change-me');

          $table_prefix = 'wp_';
          define('WP_DEBUG', false);

          if ( !defined('ABSPATH') )
              define('ABSPATH', dirname(__FILE__) . '/');

          require_once(ABSPATH . 'wp-settings.php');

    - name: Configure Nginx for WordPress
      copy:
        dest: /etc/nginx/sites-available/wordpress
        content: |
          server {
              listen 80;
              root {{ wp_install_dir }};
              index index.php index.html;
              server_name _;

              location / {
                  try_files $uri $uri/ /index.php?$args;
              }

              location ~ \.php$ {
                  include snippets/fastcgi-php.conf;
                  fastcgi_pass unix:/run/php/php-fpm.sock;
              }

              location ~ /\.ht {
                  deny all;
              }
          }

    - name: Enable WordPress site
      file:
        src: /etc/nginx/sites-available/wordpress
        dest: /etc/nginx/sites-enabled/wordpress
        state: link
        force: true

    - name: Remove default Nginx site
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: Restart Nginx and PHP-FPM
      service:
        name: "{{ item }}"
        state: restarted
      loop:
        - nginx
        - php-fpm
