


---
- name: Install Zabbix on Ubuntu 22.04
  hosts: all
  become: true

  vars:
    ansible_python_interpreter: /usr/bin/python3
    zabbix_db_password: "zabbix123"
    ansible_remote_tmp: "/var/tmp/.ansible/tmp"

  environment:
    PYTHONWARNINGS: "ignore"

  tasks:

    # --- Basic system setup ---
    - name: Configure resolv.conf with Google DNS
      shell: echo nameserver 8.8.8.8 > /etc/resolv.conf

    - name: Clear apt proxy settings
      shell: echo > /etc/apt/apt.conf.d/90curtin-aptproxy

    - name: Update apt cache
      apt:
        update_cache: yes

    # --- Install PostgreSQL ---
    - name: Install PostgreSQL
      apt:
        name: postgresql
        state: present

    # --- Install Zabbix repo ---
    - name: Download Zabbix release package
      get_url:
        url: https://repo.zabbix.com/zabbix/7.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_latest+ubuntu22.04_all.deb
        dest: /tmp/zabbix-release.deb

    - name: Install Zabbix release package
      apt:
        deb: /tmp/zabbix-release.deb
        state: present

    - name: Update apt cache after Zabbix repo
      apt:
        update_cache: yes

    # --- Install Zabbix packages ---
    - name: Install required packages
      apt:
        name:
          - zabbix-server-pgsql
          - zabbix-frontend-php
          - php-pgsql
          - zabbix-apache-conf
          - zabbix-sql-scripts
          - zabbix-agent
        state: present

    # --- PostgreSQL setup ---
    - name: Get PostgreSQL version
      shell: ls -1 /etc/postgresql/ | sort -V | tail -n 1
      register: pg_version
      changed_when: false

    - name: Configure PostgreSQL authentication
      lineinfile:
        path: "/etc/postgresql/{{ pg_version.stdout }}/main/pg_hba.conf"
        regexp: "^(host|local).*all.*all.*"
        line: "{{ item }}"
        backup: yes
      loop:
        - "local   all             all                                     md5"
        - "host    all             all             127.0.0.1/32            md5"
      ignore_errors: yes

    - name: Restart PostgreSQL
      systemd:
        name: postgresql
        state: restarted

    # CORRECTION: Créer l'utilisateur d'abord
    - name: Create Zabbix database user
      become_user: postgres
      shell: |
        psql -c "CREATE USER zabbix WITH PASSWORD '{{ zabbix_db_password }}';" 2>/dev/null || true

    # CORRECTION: Créer la base simplement
    - name: Create Zabbix database
      become_user: postgres
      shell: |
        psql -c "CREATE DATABASE zabbix OWNER zabbix;" 2>/dev/null || true

    - name: Import Zabbix schema
      become_user: postgres
      shell: |
        zcat /usr/share/zabbix-sql-scripts/postgresql/server.sql.gz | psql zabbix
      args:
        warn: false
      register: schema_import
      failed_when: schema_import.rc != 0
      changed_when: schema_import.rc == 0

    # --- Configure Zabbix ---
    - name: Configure Zabbix server DB connection
      lineinfile:
        path: /etc/zabbix/zabbix_server.conf
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      loop:
        - { regexp: '^DBHost=', line: 'DBHost=localhost' }
        - { regexp: '^DBName=', line: 'DBName=zabbix' }
        - { regexp: '^DBUser=', line: 'DBUser=zabbix' }
        - { regexp: '^DBPassword=', line: 'DBPassword={{ zabbix_db_password }}' }

    - name: Set PHP timezone
      lineinfile:
        path: /etc/php/8.1/apache2/php.ini
        regexp: "^;?date.timezone ="
        line: "date.timezone = UTC"

    - name: Configure Apache for Zabbix
      copy:
        dest: /etc/zabbix/apache.conf
        content: |
          Alias /zabbix /usr/share/zabbix
          <Directory "/usr/share/zabbix">
              Options FollowSymLinks
              AllowOverride None
              Require all granted
              <IfModule mod_php.c>
                  php_value max_execution_time 300
                  php_value memory_limit 128M
                  php_value post_max_size 16M
                  php_value upload_max_filesize 2M
                  php_value max_input_time 300
                  php_value max_input_vars 10000
                  php_value always_populate_raw_post_data -1
              </IfModule>
          </Directory>

    - name: Start Zabbix services
      systemd:
        name: "{{ item }}"
        state: restarted
        enabled: yes
      loop:
        - zabbix-server
        - zabbix-agent
        - apache2

    - name: Wait for Zabbix web interface
      uri:
        url: http://localhost/zabbix/
        status_code: 200
        timeout: 300
      register: result
      until: result.status == 200
      retries: 60
      delay: 5
      ignore_errors: yes

    - name: Clean up downloaded files
      file:
        path: /tmp/zabbix-release.deb
        state: absent

    - name: Print installation complete message
      debug:
        msg:
          - "Zabbix has been installed successfully."
          - "Access Zabbix at http://localhost/zabbix"
          - "Default credentials:"
          - "Username: Admin"
          - "Password: zabbix"
