---
- name: Install Zabbix on Ubuntu 22.04
  hosts: all
  become: true

  vars:
    ansible_python_interpreter: /usr/bin/python3
    zabbix_db_password: "zabbix123"
    ansible_remote_tmp: "/var/tmp/.ansible/tmp"

  environment:
    PYTHONWARNINGS: "ignore"

  tasks:

    # --- Basic system setup ---
    - name: Configure resolv.conf with Google DNS
      shell: echo nameserver 8.8.8.8 > /etc/resolv.conf

    - name: Clear apt proxy settings
      shell: echo > /etc/apt/apt.conf.d/90curtin-aptproxy

    - name: Update apt cache
      apt:
        update_cache: yes

    # --- Install PostgreSQL ---
    - name: Install PostgreSQL
      apt:
        name: postgresql
        state: present

    # --- Install Zabbix repo ---
    - name: Download Zabbix release package
      get_url:
        url: https://repo.zabbix.com/zabbix/7.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_latest+ubuntu22.04_all.deb
        dest: /tmp/zabbix-release.deb

    - name: Install Zabbix release package
      apt:
        deb: /tmp/zabbix-release.deb
        state: present

    - name: Update apt cache after Zabbix repo
      apt:
        update_cache: yes

    # --- Install Zabbix packages ---
    - name: Install required packages
      apt:
        name:
          - zabbix-server-pgsql
          - zabbix-frontend-php
          - php-pgsql
          - zabbix-apache-conf
          - zabbix-sql-scripts
          - zabbix-agent
        state: present

    # --- PostgreSQL setup ---
    - name: Get PostgreSQL version
      shell: ls -1 /etc/postgresql/ | sort -V | tail -n 1
      register: pg_version
      changed_when: false

    - name: Configure PostgreSQL authentication
      lineinfile:
        path: "/etc/postgresql/{{ pg_version.stdout }}/main/pg_hba.conf"
        regexp: "^(host|local).*all.*all.*"
        line: "{{ item }}"
        backup: yes
      loop:
        - "local   all             all                                     md5"
        - "host    all             all             127.0.0.1/32            md5"
      ignore_errors: yes

    - name: Restart PostgreSQL
      systemd:
        name: postgresql
        state: restarted

    # Créer l'utilisateur d'abord
    - name: Create Zabbix database user
      become_user: postgres
      shell: |
        psql -c "CREATE USER zabbix WITH PASSWORD '{{ zabbix_db_password }}';" 2>/dev/null || true

    # Créer la base simplement
    - name: Create Zabbix database
      become_user: postgres
      shell: |
        psql -c "CREATE DATABASE zabbix OWNER zabbix;" 2>/dev/null || true

    # Importer le schéma
    - name: Import Zabbix schema
      become_user: postgres
      shell: |
        zcat /usr/share/zabbix-sql-scripts/postgresql/server.sql.gz | psql zabbix
      register: schema_import
      changed_when: schema_import.rc == 0
      failed_when: schema_import.rc != 0

    # ✅ AJOUT: Donner tous les privilèges à l'utilisateur zabbix
    - name: Grant all privileges to zabbix user on database
      become_user: postgres
      shell: |
        psql -d zabbix -c "GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO zabbix;"
        psql -d zabbix -c "GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO zabbix;"
      ignore_errors: true

    # --- AJOUT: Attendre que PostgreSQL soit prêt ---
    - name: Wait for PostgreSQL to be ready
      shell: |
        sleep 3
        for i in {1..10}; do
          if pg_isready -h localhost; then
            exit 0
          fi
          sleep 2
        done
        exit 1
      ignore_errors: true

    # --- Configure Zabbix ---
    - name: Configure Zabbix server DB connection
      lineinfile:
        path: /etc/zabbix/zabbix_server.conf
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      loop:
        - { regexp: '^#?DBHost=', line: 'DBHost=localhost' }
        - { regexp: '^#?DBName=', line: 'DBName=zabbix' }
        - { regexp: '^#?DBUser=', line: 'DBUser=zabbix' }
        - { regexp: '^#?DBPassword=', line: 'DBPassword={{ zabbix_db_password }}' }

    # --- AJOUT: Vérifier la configuration Zabbix ---
    - name: Test Zabbix server configuration
      shell: |
        sudo -u zabbix /usr/sbin/zabbix_server -c /etc/zabbix/zabbix_server.conf -R config_cache_reload
      register: zabbix_test
      changed_when: false
      ignore_errors: true

    - name: Show Zabbix config test result
      debug:
        var: zabbix_test.stdout_lines

    - name: Set PHP timezone
      lineinfile:
        path: /etc/php/8.1/apache2/php.ini
        regexp: "^;?date.timezone ="
        line: "date.timezone = UTC"

    - name: Configure Apache for Zabbix
      copy:
        dest: /etc/zabbix/apache.conf
        content: |
          Alias /zabbix /usr/share/zabbix
          <Directory "/usr/share/zabbix">
              Options FollowSymLinks
              AllowOverride None
              Require all granted
              <IfModule mod_php.c>
                  php_value max_execution_time 300
                  php_value memory_limit 128M
                  php_value post_max_size 16M
                  php_value upload_max_filesize 2M
                  php_value max_input_time 300
                  php_value max_input_vars 10000
                  php_value always_populate_raw_post_data -1
              </IfModule>
          </Directory>

    # --- MODIFIÉ: Démarrer les services avec retry ---
    - name: Start Apache first
      systemd:
        name: apache2
        state: started
        enabled: yes

    - name: Start Zabbix agent
      systemd:
        name: zabbix-agent
        state: started
        enabled: yes

    - name: Start Zabbix server with retry
      shell: |
        systemctl start zabbix-server || (sleep 5 && systemctl start zabbix-server)
      ignore_errors: true

    - name: Enable Zabbix server
      systemd:
        name: zabbix-server
        state: started
        enabled: yes

    # --- AJOUT: Vérifier l'état des services ---
    - name: Check service status
      shell: |
        echo "=== Service Status ==="
        systemctl status zabbix-server --no-pager | head -20 || true
        echo "=== Zabbix Server Logs ==="
        tail -10 /var/log/zabbix/zabbix_server.log 2>/dev/null || echo "No logs yet"
      register: service_status
      changed_when: false

    - name: Show service status
      debug:
        var: service_status.stdout_lines

    - name: Wait for Zabbix web interface
      uri:
        url: http://localhost/zabbix/
        status_code: 200
        timeout: 300
      register: result
      until: result.status == 200
      retries: 30
      delay: 10
      ignore_errors: yes

    - name: Clean up downloaded files
      file:
        path: /tmp/zabbix-release.deb
        state: absent

    - name: Print installation complete message
      debug:
        msg:
          - "Zabbix installation attempted."
          - "Access Zabbix at http://localhost/zabbix"
          - "Default credentials:"
          - "   Username: Admin"
          - " Password: zabbix"

