---
- name: Install Zabbix 7.0 on Ubuntu 22.04 
  hosts: all
  become: true

  vars:
    ansible_python_interpreter: /usr/bin/python3
    zabbix_db_password: "zabbix123"
    ansible_remote_tmp: "/var/tmp/.ansible/tmp"

  tasks:

    # --- Basic system setup ---
    - name: Configure resolv.conf with Google DNS
      copy:
        content: |
          nameserver 8.8.8.8
          nameserver 8.8.4.4
        dest: /etc/resolv.conf
        owner: root
        group: root
        mode: '0644'

    - name: Clear apt proxy settings
      file:
        path: /etc/apt/apt.conf.d/90curtin-aptproxy
        state: absent

    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    # --- Install PostgreSQL ---
    - name: Install PostgreSQL
      apt:
        name: postgresql
        state: present

    # --- Install Zabbix repository ---
    - name: Download Zabbix release package
      get_url:
        url: https://repo.zabbix.com/zabbix/7.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_latest+ubuntu22.04_all.deb
        dest: /tmp/zabbix-release.deb
        timeout: 60
        validate_certs: yes

    - name: Install Zabbix release package
      apt:
        deb: /tmp/zabbix-release.deb
        state: present

    - name: Update apt cache after Zabbix repo
      apt:
        update_cache: yes

    # --- Install Zabbix packages ---
    - name: Install required packages
      apt:
        name:
          - zabbix-server-pgsql
          - zabbix-frontend-php
          - php8.1-pgsql
          - zabbix-apache-conf
          - zabbix-sql-scripts
          - zabbix-agent
        state: present

    # --- PostgreSQL setup ---
    - name: Get PostgreSQL version
      shell: ls -1 /etc/postgresql/ | sort -V | tail -n 1
      register: pg_version
      changed_when: false

    - name: Configure PostgreSQL authentication
      lineinfile:
        path: "/etc/postgresql/{{ pg_version.stdout }}/main/pg_hba.conf"
        regexp: "^(host|local).*all.*all.*"
        line: "{{ item }}"
        backup: yes
      loop:
        - "local   all             all                                     md5"
        - "host    all             all             127.0.0.1/32            md5"
      ignore_errors: yes

    - name: Restart PostgreSQL
      systemd:
        name: postgresql
        state: restarted

    # --- Database setup ---
    - name: Create Zabbix database user
      become_user: postgres
      shell: |
        psql -c "CREATE USER zabbix WITH PASSWORD '{{ zabbix_db_password }}';" 2>/dev/null || true

    - name: Create Zabbix database
      become_user: postgres
      shell: |
        psql -c "CREATE DATABASE zabbix OWNER zabbix;" 2>/dev/null || true

    - name: Import Zabbix schema
      become_user: postgres
      shell: |
        zcat /usr/share/zabbix-sql-scripts/postgresql/server.sql.gz | psql zabbix
      register: schema_import
      changed_when: schema_import.rc == 0
      failed_when: schema_import.rc != 0

    - name: Grant all privileges to zabbix user on database
      become_user: postgres
      shell: |
        psql -d zabbix -c "GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO zabbix;"
        psql -d zabbix -c "GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO zabbix;"
      ignore_errors: true

    # --- Wait for PostgreSQL ---
    - name: Wait for PostgreSQL to be ready
      shell: |
        sleep 3
        for i in {1..10}; do
          if pg_isready -h localhost; then
            exit 0
          fi
          sleep 2
        done
        exit 1
      ignore_errors: true

    # --- Configure Zabbix server ---
    - name: Configure Zabbix server database connection
      lineinfile:
        path: /etc/zabbix/zabbix_server.conf
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      loop:
        - { regexp: '^#?DBHost=', line: 'DBHost=localhost' }
        - { regexp: '^#?DBName=', line: 'DBName=zabbix' }
        - { regexp: '^#?DBUser=', line: 'DBUser=zabbix' }
        - { regexp: '^#?DBPassword=', line: 'DBPassword={{ zabbix_db_password }}' }

    # --- FIX CRITICAL: Set proper permissions ---
    - name: Set correct permissions for Zabbix configuration
      file:
        path: /etc/zabbix/zabbix_server.conf
        owner: zabbix
        group: zabbix
        mode: '0640'

    # --- PRODUCTION: Validate Zabbix configuration ---
    - name: Validate Zabbix server configuration
      shell: |
        # Test configuration with syntax check
        sudo -u zabbix /usr/sbin/zabbix_server -c /etc/zabbix/zabbix_server.conf -t 2>&1 | grep -E "(configuration|database|successful)" || echo "Configuration test completed"
      register: config_validation
      changed_when: false
      failed_when: "'invalid configuration' in config_validation.stdout or 'cannot connect' in config_validation.stdout"

    - name: Show configuration validation result
      debug:
        var: config_validation.stdout_lines

    # --- Configure PHP ---
    - name: Set PHP timezone
      lineinfile:
        path: /etc/php/8.1/apache2/php.ini
        regexp: "^;?date.timezone ="
        line: "date.timezone = UTC"

    - name: Configure PHP memory settings
      lineinfile:
        path: /etc/php/8.1/apache2/php.ini
        regexp: "^{{ item.regexp }}"
        line: "{{ item.line }}"
      loop:
        - { regexp: '^memory_limit', line: 'memory_limit = 256M' }
        - { regexp: '^post_max_size', line: 'post_max_size = 32M' }
        - { regexp: '^upload_max_filesize', line: 'upload_max_filesize = 16M' }
        - { regexp: '^max_execution_time', line: 'max_execution_time = 300' }

    # --- Configure Apache ---
    - name: Configure Apache for Zabbix
      copy:
        dest: /etc/zabbix/apache.conf
        content: |
          Alias /zabbix /usr/share/zabbix
          <Directory "/usr/share/zabbix">
              Options FollowSymLinks
              AllowOverride None
              Require all granted
              <IfModule mod_php.c>
                  php_value max_execution_time 300
                  php_value memory_limit 256M
                  php_value post_max_size 32M
                  php_value upload_max_filesize 16M
                  php_value max_input_time 300
                  php_value max_input_vars 10000
                  php_value always_populate_raw_post_data -1
              </IfModule>
          </Directory>

    # --- Start services ---
    - name: Start Apache first
      systemd:
        name: apache2
        state: started
        enabled: yes

    - name: Start Zabbix agent
      systemd:
        name: zabbix-agent
        state: started
        enabled: yes

    - name: Start Zabbix server with retry
      shell: |
        systemctl start zabbix-server || (sleep 5 && systemctl start zabbix-server)
      ignore_errors: true

    - name: Enable Zabbix server
      systemd:
        name: zabbix-server
        state: started
        enabled: yes

    # --- Verify installation ---
    - name: Check service status
      shell: |
        echo "=== Service Status ==="
        systemctl status zabbix-server --no-pager | head -20 || true
        echo "=== Zabbix Server Logs (last 10 lines) ==="
        tail -10 /var/log/zabbix/zabbix_server.log 2>/dev/null || echo "No logs yet"
      register: service_status
      changed_when: false

    - name: Show service status
      debug:
        var: service_status.stdout_lines

    - name: Wait for Zabbix web interface
      uri:
        url: http://localhost/zabbix/
        status_code: 200
        timeout: 300
      register: result
      until: result.status == 200
      retries: 30
      delay: 10
      ignore_errors: yes

    # --- Cleanup ---
    - name: Clean up downloaded files
      file:
        path: /tmp/zabbix-release.deb
        state: absent

    # --- Completion message for Morpheus ---
    - name: Print installation complete message
      debug:
        msg: |
          Zabbix 7.0 installation completed successfully on Ubuntu 22.04
          
          Installation Details:
          - Zabbix Version: 7.0
          - Ubuntu Version: 22.04 LTS
          - Database: PostgreSQL
          - PHP Version: 8.1
          
          Access Information:
          - Web Interface: http://{{ ansible_default_ipv4.address }}/zabbix
          - Default Credentials: Admin / zabbix
          
          Database Configuration:
          - Database Name: zabbix
          - Database User: zabbix
          - Database Password: {{ zabbix_db_password }}
          
